INSERT INTO QUARTO (id_quarto, id_propriedade, tipo, qntd_cama, tipo_cama1, tipo_cama2, banheiro_priv) VALUES
(1, 1, 'Suíte Master', 2, 'Queen', 'Solteiro', TRUE),
(2, 1, 'Quarto Simples', 1, 'Solteiro', NULL, TRUE),
(3, 2, 'Cabana Familiar', 3, 'Casal', 'Solteiro', FALSE),
(4, 2, 'Cabana Individual', 1, 'Solteiro', NULL, TRUE),
(5, 3, 'Estúdio Luxo', 1, 'Queen', NULL, TRUE),
(6, 3, 'Quarto Compacto', 1, 'Solteiro', NULL, TRUE),
(7, 4, 'Chalé Romântico', 1, 'Casal', NULL, TRUE),
(8, 4, 'Chalé Família', 2, 'Casal', 'Beliche', FALSE),
(9, 5, 'Suíte Urbana', 1, 'Casal', NULL, TRUE),
(10, 5, 'Loft Executivo', 1, 'Solteiro', NULL, TRUE),
(11, 6, 'Colonial Duplo', 2, 'Solteiro', 'Solteiro', FALSE),
(12, 6, 'Colonial Casal', 1, 'Casal', NULL, TRUE),
(13, 7, 'Quarto Pousada 1', 2, 'Solteiro', 'Solteiro', FALSE),
(14, 7, 'Quarto Pousada 2', 1, 'Casal', NULL, TRUE),
(15, 8, 'Vista Mar Luxo', 1, 'Queen', NULL, TRUE),
(16, 8, 'Vista Mar Família', 3, 'Casal', 'Solteiro', FALSE),
(17, 9, 'Apartamento Compacto', 1, 'Solteiro', NULL, TRUE),
(18, 9, 'Apartamento Duplo', 2, 'Solteiro', 'Solteiro', TRUE),
(19, 10, 'Quarto Cerrado A', 2, 'Casal', 'Solteiro', FALSE),
(20, 10, 'Quarto Cerrado B', 1, 'Casal', NULL, TRUE);
