CREATE TABLE Propriedade (
  id_propriedade SERIAL NOT NULL,
  nome VARCHAR(200) NOT NULL,
  cidade VARCHAR(100) NOT NULL,
  estado VARCHAR(50) NOT NULL,
  pais VARCHAR(50) NOT NULL,
  cep VARCHAR (10) NOT NULL,
  bairro VARCHAR(150) NOT NULL,
  ponto_de_referencia VARCHAR(500),
  tipo VARCHAR(20) NOT NULL,
  n_quartos INT NOT NULL,
  n_banheiros INT NOT NULL,
  preco_noite DECIMAL(50,2) NOT NULL,
  max_hospedes INT NOT NULL,
  min_noites INT NOT NULL,
  max_noites INT NOT NULL,
  taxa_limpeza DECIMAL(50,2),
  datas_disp DATE,
  hor_checkin DATE,
  hor_checkout DATE,
  regras VARCHAR(500),
  comodidades VARCHAR(500),
  CONSTRAINT pk_propriedade PRIMARY KEY (id_propriedade)
)