INSERT INTO REGRA (Tipo) VALUES
('Regra de Matrícula I'),
('Regra de Matrícula II'),
('Regra de Matrícula III'),
('Regra de Matrícula IV'),
('Regra de Matrícula V'),
('Regra de Matrícula VI'),
('Regra de Matrícula VII'),
('Regra de Matrícula VIII'),
('Regra de Matrícula IX'),
('Regra de Matrícula X'),
('Regra de Matrícula XI'),
('Regra de Matrícula XII'),
('Regra de Matrícula XIII'),
('Regra de Matrícula XIV'),
('Regra de Matrícula XV'),
('Regra de Frequência I'),
('Regra de Frequência II'),
('Regra de Frequência III'),
('Regra de Frequência IV'),
('Regra de Frequência V'),
('Regra de Frequência VI'),
('Regra de Frequência VII'),
('Regra de Frequência VIII'),
('Regra de Frequência IX'),
('Regra de Frequência X'),
('Regra de Frequência XI'),
('Regra de Frequência XII'),
('Regra de Frequência XIII'),
('Regra de Frequência XIV'),
('Regra de Frequência XV'),
('Regra de Avaliação I'),
('Regra de Avaliação II'),
('Regra de Avaliação III'),
('Regra de Avaliação IV'),
('Regra de Avaliação V'),
('Regra de Avaliação VI'),
('Regra de Avaliação VII'),
('Regra de Avaliação VIII'),
('Regra de Avaliação IX'),
('Regra de Avaliação X'),
('Regra de Avaliação XI'),
('Regra de Avaliação XII'),
('Regra de Avaliação XIII'),
('Regra de Avaliação XIV'),
('Regra de Avaliação XV'),
('Regra de Comportamento I'),
('Regra de Comportamento II'),
('Regra de Comportamento III'),
('Regra de Comportamento IV'),
('Regra de Comportamento V'),
('Regra de Comportamento VI'),
('Regra de Comportamento VII'),
('Regra de Comportamento VIII'),
('Regra de Comportamento IX'),
('Regra de Comportamento X'),
('Regra de Comportamento XI'),
('Regra de Comportamento XII'),
('Regra de Comportamento XIII'),
('Regra de Comportamento XIV'),
('Regra de Comportamento XV'),
('Regra de Disciplina I'),
('Regra de Disciplina II'),
('Regra de Disciplina III'),
('Regra de Disciplina IV'),
('Regra de Disciplina V'),
('Regra de Disciplina VI'),
('Regra de Disciplina VII'),
('Regra de Disciplina VIII'),
('Regra de Disciplina IX'),
('Regra de Disciplina X'),
('Regra de Disciplina XI'),
('Regra de Disciplina XII'),
('Regra de Disciplina XIII'),
('Regra de Disciplina XIV'),
('Regra de Disciplina XV'),
('Regra de Reprovação I'),
('Regra de Reprovação II'),
('Regra de Reprovação III'),
('Regra de Reprovação IV'),
('Regra de Reprovação V'),
('Regra de Reprovação VI'),
('Regra de Reprovação VII'),
('Regra de Reprovação VIII'),
('Regra de Reprovação IX'),
('Regra de Reprovação X'),
('Regra de Reprovação XI'),
('Regra de Reprovação XII'),
('Regra de Reprovação XIII'),
('Regra de Reprovação XIV'),
('Regra de Reprovação XV'),
('Regra de Aprovação I'),
('Regra de Aprovação II'),
('Regra de Aprovação III'),
('Regra de Aprovação IV'),
('Regra de Aprovação V'),
('Regra de Aprovação VI'),
('Regra de Aprovação VII'),
('Regra de Aprovação VIII'),
('Regra de Aprovação IX'),
('Regra de Aprovação X'),
('Regra de Aprovação XI'),
('Regra de Aprovação XII'),
('Regra de Aprovação XIII'),
('Regra de Aprovação XIV'),
('Regra de Aprovação XV'),
('Regra de Transferência I'),
('Regra de Transferência II'),
('Regra de Transferência III'),
('Regra de Transferência IV'),
('Regra de Transferência V'),
('Regra de Transferência VI'),
('Regra de Transferência VII'),
('Regra de Transferência VIII'),
('Regra de Transferência IX'),
('Regra de Transferência X'),
('Regra de Transferência XI'),
('Regra de Transferência XII'),
('Regra de Transferência XIII'),
('Regra de Transferência XIV'),
('Regra de Transferência XV'),
('Regra de Cancelamento I'),
('Regra de Cancelamento II'),
('Regra de Cancelamento III'),
('Regra de Cancelamento IV'),
('Regra de Cancelamento V'),
('Regra de Cancelamento VI'),
('Regra de Cancelamento VII'),
('Regra de Cancelamento VIII'),
('Regra de Cancelamento IX'),
('Regra de Cancelamento X'),
('Regra de Cancelamento XI'),
('Regra de Cancelamento XII'),
('Regra de Cancelamento XIII'),
('Regra de Cancelamento XIV'),
('Regra de Cancelamento XV'),
('Regra de Frequência Mínima I'),
('Regra de Frequência Mínima II'),
('Regra de Frequência Mínima III'),
('Regra de Frequência Mínima IV'),
('Regra de Frequência Mínima V'),
('Regra de Frequência Mínima VI'),
('Regra de Frequência Mínima VII'),
('Regra de Frequência Mínima VIII'),
('Regra de Frequência Mínima IX'),
('Regra de Frequência Mínima X'),
('Regra de Frequência Mínima XI'),
('Regra de Frequência Mínima XII'),
('Regra de Frequência Mínima XIII'),
('Regra de Frequência Mínima XIV'),
('Regra de Frequência Mínima XV'),
('Regra de Nota Mínima I'),
('Regra de Nota Mínima II'),
('Regra de Nota Mínima III'),
('Regra de Nota Mínima IV'),
('Regra de Nota Mínima V'),
('Regra de Nota Mínima VI'),
('Regra de Nota Mínima VII'),
('Regra de Nota Mínima VIII'),
('Regra de Nota Mínima IX'),
('Regra de Nota Mínima X'),
('Regra de Nota Mínima XI'),
('Regra de Nota Mínima XII'),
('Regra de Nota Mínima XIII'),
('Regra de Nota Mínima XIV'),
('Regra de Nota Mínima XV'),
('Regra de Prova Final I'),
('Regra de Prova Final II'),
('Regra de Prova Final III'),
('Regra de Prova Final IV'),
('Regra de Prova Final V'),
('Regra de Prova Final VI'),
('Regra de Prova Final VII'),
('Regra de Prova Final VIII'),
('Regra de Prova Final IX'),
('Regra de Prova Final X'),
('Regra de Prova Final XI'),
('Regra de Prova Final XII'),
('Regra de Prova Final XIII'),
('Regra de Prova Final XIV'),
('Regra de Prova Final XV'),
('Regra de Trabalho de Conclusão I'),
('Regra de Trabalho de Conclusão II'),
('Regra de Trabalho de Conclusão III'),
('Regra de Trabalho de Conclusão IV'),
('Regra de Trabalho de Conclusão V'),
('Regra de Trabalho de Conclusão VI'),
('Regra de Trabalho de Conclusão VII'),
('Regra de Trabalho de Conclusão VIII'),
('Regra de Trabalho de Conclusão IX'),
('Regra de Trabalho de Conclusão X'),
('Regra de Trabalho de Conclusão XI'),
('Regra de Trabalho de Conclusão XII'),
('Regra de Trabalho de Conclusão XIII'),
('Regra de Trabalho de Conclusão XIV'),
('Regra de Trabalho de Conclusão XV'),
('Regra de Estágio I'),
('Regra de Estágio II'),
('Regra de Estágio III'),
('Regra de Estágio IV'),
('Regra de Estágio V'),
('Regra de Estágio VI'),
('Regra de Estágio VII'),
('Regra de Estágio VIII'),
('Regra de Estágio IX'),
('Regra de Estágio X'),
('Regra de Estágio XI'),
('Regra de Estágio XII'),
('Regra de Estágio XIII'),
('Regra de Estágio XIV'),
('Regra de Estágio XV'),
('Regra de Atividades Complementares I'),
('Regra de Atividades Complementares II'),
('Regra de Atividades Complementares III'),
('Regra de Atividades Complementares IV'),
('Regra de Atividades Complementares V'),
('Regra de Atividades Complementares VI'),
('Regra de Atividades Complementares VII'),
('Regra de Atividades Complementares VIII'),
('Regra de Atividades Complementares IX'),
('Regra de Atividades Complementares X'),
('Regra de Atividades Complementares XI'),
('Regra de Atividades Complementares XII'),
('Regra de Atividades Complementares XIII'),
('Regra de Atividades Complementares XIV'),
('Regra de Atividades Complementares XV');