INSERT INTO INFRAESTRUTURA (Tipo) VALUES
('Sala de Informática'),
('Laboratório de Microbiologia'),
('Laboratório de Física'),
('Biblioteca'),
('Auditório'),
('Sala de Artes'),
('Laboratório de Química'),
('Laboratório de Biologia'),
('Sala de Música'),
('Quadra Poliesportiva'),
('Laboratório de Robótica'),
('Laboratório de Matemática'),
('Sala de Leitura'),
('Sala de Estudo Individual'),
('Sala de Estudo em Grupo'),
('Refeitório'),
('Cantina'),
('Sala de Projeção'),
('Laboratório de Línguas'),
('Laboratório de Geografia'),
('Laboratório de História'),
('Sala de Coordenação'),
('Sala dos Professores'),
('Laboratório de Programação'),
('Laboratório de Redes'),
('Sala de Atendimento Psicológico'),
('Laboratório de Engenharia'),
('Sala de Defesas de TCC'),
('Laboratório de Análises Clínicas'),
('Estúdio de Gravação'),
('Laboratório de Design Gráfico'),
('Oficina de Mecânica'),
('Laboratório de Automação'),
('Sala de Jogos Educativos'),
('Laboratório de Realidade Virtual'),
('Laboratório de Inteligência Artificial'),
('Laboratório de Eletrônica'),
('Sala de Empreendedorismo'),
('Laboratório de Produção de Vídeo'),
('Sala de Modelagem 3D'),
('Laboratório de Construção Civil'),
('Laboratório de Fotografia'),
('Laboratório de Meio Ambiente'),
('Sala de Estudos Interdisciplinares'),
('Sala de Desenvolvimento de Software'),
('Laboratório de Nutrição'),
('Laboratório de Análise de Dados'),
('Sala de Impressão 3D'),
('Laboratório de Engenharia Química'),
('Laboratório de Ciência dos Materiais');
