INSERT INTO MATERIAL (Tipo) VALUES
('Microbiologia Volume 1'),
('Microbiologia Volume 2'),
('Física Moderna'),
('Física Clássica'),
('Química Orgânica'),
('Química Inorgânica'),
('Biologia Celular'),
('Biologia Molecular'),
('Matemática Discreta'),
('Cálculo Diferencial e Integral'),
('Álgebra Linear'),
('Estatística Aplicada'),
('Introdução à Programação'),
('Estruturas de Dados'),
('Algoritmos e Lógica de Programação'),
('Sistemas Operacionais'),
('Redes de Computadores'),
('Banco de Dados'),
('Engenharia de Software'),
('Inteligência Artificial'),
('Aprendizado de Máquina'),
('Linguagens de Programação'),
('Teoria dos Grafos'),
('Análise Numérica'),
('Física Experimental'),
('Geometria Analítica'),
('História do Brasil'),
('História Mundial'),
('Filosofia Contemporânea'),
('Sociologia Geral'),
('Psicologia do Desenvolvimento'),
('Antropologia Cultural'),
('Direito Constitucional'),
('Direito Civil'),
('Administração Pública'),
('Marketing Estratégico'),
('Economia Internacional'),
('Finanças Corporativas'),
('Contabilidade Básica'),
('Educação Ambiental'),
('Pedagogia'),
('Didática e Prática de Ensino'),
('Metodologia Científica'),
('Técnicas de Pesquisa'),
('Comunicação Oral e Escrita'),
('Literatura Brasileira'),
('Literatura Inglesa'),
('Arte e Cultura'),
('Música e Sociedade'),
('Design Gráfico'),
('Fotografia Digital'),
('Cinema e Audiovisual'),
('Produção Editorial'),
('Jornalismo Investigativo'),
('Relações Internacionais'),
('Política Brasileira'),
('Geografia Física'),
('Geografia Humana'),
('Meteorologia'),
('Astronomia'),
('Ecologia'),
('Genética'),
('Imunologia'),
('Farmacologia'),
('Anatomia Humana'),
('Fisiologia'),
('Nutrição'),
('Enfermagem Básica'),
('Medicina Interna'),
('Cirurgia Geral'),
('Odontologia'),
('Veterinária'),
('Engenharia Civil'),
('Engenharia Elétrica'),
('Engenharia Mecânica'),
('Engenharia Química'),
('Engenharia Ambiental'),
('Arquitetura e Urbanismo'),
('Matemática Financeira'),
('Estatística para Engenharia'),
('Probabilidade'),
('Análise Estatística'),
('Marketing Digital'),
('Empreendedorismo'),
('Gestão de Projetos'),
('Qualidade Total'),
('Logística Empresarial'),
('Gestão de Recursos Humanos'),
('Comércio Exterior'),
('Direito do Trabalho'),
('Processos Administrativos'),
('Ética Profissional'),
('Técnicas de Negociação'),
('Segurança do Trabalho'),
('Saúde Pública'),
('Educação Física'),
('Psicologia Organizacional'),
('Psicopedagogia'),
('Linguística Aplicada'),
('Gramática Avançada'),
('Inglês Técnico'),
('Espanhol para Negócios'),
('Francês Básico'),
('Alemão Intermediário'),
('Italiano'),
('Japonês'),
('Chinês Mandarim'),
('Português para Estrangeiros'),
('Tecnologia da Informação'),
('Computação em Nuvem'),
('Desenvolvimento Web'),
('Programação Mobile'),
('Segurança da Informação'),
('Criptografia'),
('Robótica'),
('Automação Industrial'),
('Inteligência Computacional'),
('Big Data'),
('Internet das Coisas'),
('Blockchain'),
('Realidade Virtual'),
('Realidade Aumentada'),
('Design de Jogos'),
('Animação Digital'),
('Edição de Vídeo'),
('Produção Musical'),
('Teoria da Música'),
('Composição Musical'),
('Dança Contemporânea'),
('Teatro'),
('Cinema'),
('Estética'),
('História da Arte'),
('Arqueologia'),
('Museologia'),
('Conservação de Bens Culturais'),
('Educação Inclusiva'),
('Psicomotricidade'),
('Neuropsicologia'),
('Terapia Ocupacional'),
('Fonoaudiologia'),
('Ciência da Computação'),
('Engenharia de Dados'),
('Sistemas Embarcados'),
('Redes Neurais'),
('Visão Computacional'),
('Processamento de Imagem'),
('Banco de Dados Avançado'),
('Engenharia de Software Ágil'),
('Testes de Software'),
('Desenvolvimento de APIs'),
('Programação Orientada a Objetos'),
('Desenvolvimento Front-end'),
('Desenvolvimento Back-end'),
('Computação Gráfica'),
('Simulação Computacional'),
('Matemática Aplicada'),
('Cálculo Numérico'),
('Tópicos Especiais em Física'),
('Química Analítica'),
('Bioquímica'),
('Genômica'),
('Proteômica'),
('Biotecnologia'),
('Ecossistemas'),
('Sustentabilidade'),
('Energia Renovável'),
('Tecnologia Ambiental'),
('Gestão de Resíduos'),
('Legislação Ambiental'),
('Educação para a Cidadania'),
('Antropologia Urbana'),
('Sociologia Rural'),
('Geopolítica'),
('Demografia'),
('Estudos Culturais'),
('Comunicação e Cultura'),
('Produção Cultural'),
('Estudos de Gênero'),
('Teoria da Comunicação'),
('Publicidade e Propaganda'),
('Marketing de Serviços'),
('Comportamento do Consumidor'),
('Administração Financeira'),
('Auditoria'),
('Tributação'),
('Planejamento Estratégico'),
('Governança Corporativa'),
('Direitos Humanos'),
('Relações Trabalhistas'),
('Legislação Empresarial');
