INSERT INTO DISCIPLINA (Nome, Codigo_Disc, Qntd_Aulas, Nome_Unidade) VALUES
('Matemática Básica', 'FIS100', 32, 'Escola Central SP'),
('Português I', 'POR101', 25, 'Centro Educacional RS'),
('História Geral', 'ART102', 36, 'Escola Técnica SSA'),
('Geografia I', 'QUI103', 35, 'Centro Educacional RS'),
('Física Básica', 'QUI104', 31, 'Instituto Norte'),
('Química I', 'GEO105', 37, 'Instituto Norte'),
('Biologia Celular', 'MAT106', 22, 'Escola Técnica SSA'),
('Inglês Básico', 'QUI107', 33, 'Unidade Zona Sul RJ'),
('Educação Física', 'ART108', 29, 'Instituto Sul RJ'),
('Artes Visuais', 'EDF109', 31, 'Instituto Norte'),
('Matemática Avançada', 'BIO110', 29, 'Instituto Norte'),
('Português II', 'FIS111', 34, 'Centro Educacional BH'),
('História do Brasil', 'ING112', 30, 'Instituto Norte'),
('Geografia II', 'EDF113', 33, 'Instituto Sul RJ'),
('Física II', 'GEO114', 31, 'Centro Educacional RS'),
('Química Orgânica', 'ART115', 22, 'Centro Educacional BH'),
('Biologia Molecular', 'ART116', 29, 'Centro Educacional BH'),
('Inglês Intermediário', 'ART117', 31, 'Instituto Sul RJ'),
('Educação Artística', 'HIS118', 34, 'Escola Técnica SSA'),
('Teatro', 'INF119', 38, 'Escola Central SP'),
('Programação I', 'HIS120', 33, 'Instituto Sul RJ'),
('Banco de Dados', 'GEO121', 39, 'Centro Educacional BH'),
('Redes de Computadores', 'ING122', 26, 'Escola Técnica SSA'),
('Sistemas Operacionais', 'MAT123', 20, 'Escola Técnica SSA'),
('Algoritmos', 'INF124', 20, 'Instituto Norte'),
('Lógica de Programação', 'FIS125', 37, 'Instituto Sul RJ'),
('Desenvolvimento Web', 'BIO126', 25, 'Instituto Sul RJ'),
('Matemática Financeira', 'QUI127', 36, 'Centro Educacional BH'),
('Física Moderna', 'FIS128', 39, 'Centro Educacional BH'),
('Gestão de Projetos', 'FIS129', 35, 'Escola Técnica SSA'),
('Química Analítica', 'ING130', 40, 'Escola Técnica SSA'),
('Física Experimental', 'QUI131', 22, 'Escola Central SP'),
('Literatura Brasileira', 'BIO132', 32, 'Escola Técnica SSA'),
('Ciência Política', 'POR133', 29, 'Centro Educacional RS'),
('Direito Constitucional', 'ING134', 20, 'Centro Educacional RS'),
('Sociologia', 'INF135', 20, 'Escola Oeste PR'),
('Psicologia', 'ART136', 33, 'Unidade Centro PE'),
('Antropologia', 'GEO137', 27, 'Escola Técnica SSA'),
('Filosofia', 'ART138', 35, 'Unidade Zona Sul RJ'),
('Ecologia', 'BIO139', 28, 'Instituto Sul RJ'),
('Matemática Básica', 'POR140', 33, 'Unidade Leste SP'),
('Português I', 'INF141', 29, 'Instituto Norte'),
('História Geral', 'EDF142', 22, 'Instituto Sul RJ'),
('Geografia I', 'EDF143', 35, 'Unidade Centro PE'),
('Física Básica', 'HIS144', 35, 'Instituto Norte'),
('Química I', 'MAT145', 24, 'Instituto Norte'),
('Biologia Celular', 'POR146', 38, 'Unidade Zona Sul RJ'),
('Inglês Básico', 'GEO147', 25, 'Escola Central SP'),
('Educação Física', 'FIS148', 27, 'Instituto Sul RJ'),
('Artes Visuais', 'FIS149', 20, 'Centro Educacional BH'),
('Matemática Avançada', 'ART150', 25, 'Centro Educacional BH'),
('Português II', 'POR151', 28, 'Escola Técnica SSA'),
('História do Brasil', 'MAT152', 22, 'Unidade Leste SP'),
('Geografia II', 'BIO153', 28, 'Centro Educacional BH'),
('Física II', 'MAT154', 23, 'Unidade Centro PE'),
('Química Orgânica', 'MAT155', 27, 'Escola Técnica SSA'),
('Biologia Molecular', 'FIS156', 20, 'Instituto Norte'),
('Inglês Intermediário', 'ING157', 26, 'Unidade Centro PE'),
('Educação Artística', 'QUI158', 39, 'Centro Educacional RS'),
('Teatro', 'MAT159', 22, 'Unidade Centro PE'),
('Programação I', 'INF160', 20, 'Escola Oeste PR'),
('Banco de Dados', 'FIS161', 39, 'Instituto Norte'),
('Redes de Computadores', 'POR162', 29, 'Escola Oeste PR'),
('Sistemas Operacionais', 'MAT163', 34, 'Unidade Centro PE'),
('Algoritmos', 'GEO164', 31, 'Unidade Leste SP'),
('Lógica de Programação', 'FIS165', 22, 'Instituto Sul RJ'),
('Desenvolvimento Web', 'GEO166', 26, 'Centro Educacional BH'),
('Matemática Financeira', 'POR167', 38, 'Unidade Centro PE'),
('Física Moderna', 'HIS168', 40, 'Unidade Centro PE'),
('Gestão de Projetos', 'FIS169', 25, 'Centro Educacional RS'),
('Química Analítica', 'EDF170', 22, 'Centro Educacional RS'),
('Física Experimental', 'POR171', 24, 'Centro Educacional BH'),
('Literatura Brasileira', 'HIS172', 39, 'Centro Educacional RS'),
('Ciência Política', 'GEO173', 33, 'Centro Educacional RS'),
('Direito Constitucional', 'ART174', 39, 'Centro Educacional RS'),
('Sociologia', 'HIS175', 20, 'Escola Central SP'),
('Psicologia', 'EDF176', 39, 'Unidade Zona Sul RJ'),
('Antropologia', 'INF177', 38, 'Centro Educacional BH'),
('Filosofia', 'EDF178', 29, 'Escola Central SP'),
('Ecologia', 'FIS179', 21, 'Unidade Leste SP'),
('Matemática Básica', 'BIO180', 24, 'Escola Central SP'),
('Português I', 'FIS181', 31, 'Instituto Sul RJ'),
('História Geral', 'INF182', 40, 'Centro Educacional BH'),
('Geografia I', 'ING183', 29, 'Escola Oeste PR'),
('Física Básica', 'EDF184', 38, 'Unidade Zona Sul RJ'),
('Química I', 'MAT185', 38, 'Instituto Norte'),
('Biologia Celular', 'QUI186', 24, 'Unidade Leste SP'),
('Inglês Básico', 'EDF187', 25, 'Unidade Centro PE'),
('Educação Física', 'FIS188', 39, 'Instituto Norte'),
('Artes Visuais', 'MAT189', 33, 'Unidade Leste SP'),
('Matemática Avançada', 'MAT190', 24, 'Unidade Centro PE'),
('Português II', 'QUI191', 25, 'Escola Técnica SSA'),
('História do Brasil', 'EDF192', 25, 'Centro Educacional RS'),
('Geografia II', 'INF193', 21, 'Escola Técnica SSA'),
('Física II', 'GEO194', 27, 'Escola Central SP'),
('Química Orgânica', 'EDF195', 38, 'Unidade Centro PE'),
('Biologia Molecular', 'BIO196', 29, 'Unidade Zona Sul RJ'),
('Inglês Intermediário', 'BIO197', 32, 'Centro Educacional RS'),
('Educação Artística', 'POR198', 22, 'Unidade Zona Sul RJ'),
('Teatro', 'HIS199', 30, 'Escola Central SP'),
('Programação I', 'MAT200', 35, 'Escola Central SP'),
('Banco de Dados', 'INF201', 30, 'Escola Central SP'),
('Redes de Computadores', 'EDF202', 37, 'Unidade Leste SP'),
('Sistemas Operacionais', 'ART203', 38, 'Unidade Zona Sul RJ'),
('Algoritmos', 'ING204', 34, 'Centro Educacional BH'),
('Lógica de Programação', 'HIS205', 40, 'Unidade Zona Sul RJ'),
('Desenvolvimento Web', 'QUI206', 34, 'Centro Educacional BH'),
('Matemática Financeira', 'HIS207', 33, 'Escola Oeste PR'),
('Física Moderna', 'MAT208', 40, 'Unidade Centro PE'),
('Gestão de Projetos', 'QUI209', 36, 'Instituto Norte'),
('Química Analítica', 'ART210', 24, 'Unidade Leste SP'),
('Física Experimental', 'ART211', 20, 'Escola Oeste PR'),
('Literatura Brasileira', 'GEO212', 34, 'Unidade Zona Sul RJ'),
('Ciência Política', 'ING213', 26, 'Instituto Sul RJ'),
('Direito Constitucional', 'POR214', 37, 'Escola Oeste PR'),
('Sociologia', 'POR215', 23, 'Escola Técnica SSA'),
('Psicologia', 'EDF216', 31, 'Unidade Centro PE'),
('Antropologia', 'POR217', 38, 'Escola Central SP'),
('Filosofia', 'GEO218', 26, 'Centro Educacional RS'),
('Ecologia', 'POR219', 34, 'Unidade Centro PE'),
('Matemática Básica', 'ART220', 25, 'Instituto Norte'),
('Português I', 'HIS221', 40, 'Centro Educacional BH'),
('História Geral', 'GEO222', 28, 'Unidade Leste SP'),
('Geografia I', 'POR223', 28, 'Unidade Leste SP'),
('Física Básica', 'MAT224', 40, 'Escola Central SP'),
('Química I', 'FIS225', 38, 'Centro Educacional RS'),
('Biologia Celular', 'EDF226', 27, 'Escola Oeste PR'),
('Inglês Básico', 'ING227', 26, 'Escola Oeste PR'),
('Educação Física', 'HIS228', 29, 'Unidade Leste SP'),
('Artes Visuais', 'QUI229', 38, 'Unidade Zona Sul RJ'),
('Matemática Avançada', 'GEO230', 35, 'Escola Técnica SSA'),
('Português II', 'EDF231', 35, 'Escola Técnica SSA'),
('História do Brasil', 'EDF232', 35, 'Instituto Norte'),
('Geografia II', 'FIS233', 20, 'Unidade Zona Sul RJ'),
('Física II', 'ING234', 30, 'Escola Técnica SSA'),
('Química Orgânica', 'HIS235', 37, 'Centro Educacional RS'),
('Biologia Molecular', 'GEO236', 21, 'Instituto Norte'),
('Inglês Intermediário', 'HIS237', 21, 'Escola Central SP'),
('Educação Artística', 'HIS238', 28, 'Escola Central SP'),
('Teatro', 'BIO239', 36, 'Escola Técnica SSA'),
('Programação I', 'HIS240', 20, 'Escola Central SP'),
('Banco de Dados', 'GEO241', 35, 'Centro Educacional RS'),
('Redes de Computadores', 'ART242', 38, 'Instituto Sul RJ'),
('Sistemas Operacionais', 'BIO243', 40, 'Unidade Centro PE'),
('Algoritmos', 'POR244', 40, 'Unidade Zona Sul RJ'),
('Lógica de Programação', 'FIS245', 36, 'Escola Técnica SSA'),
('Desenvolvimento Web', 'BIO246', 31, 'Instituto Norte'),
('Matemática Financeira', 'INF247', 36, 'Escola Central SP'),
('Física Moderna', 'INF248', 36, 'Centro Educacional BH'),
('Gestão de Projetos', 'GEO249', 35, 'Instituto Sul RJ'),
('Química Analítica', 'EDF250', 28, 'Escola Central SP'),
('Física Experimental', 'INF251', 30, 'Escola Oeste PR'),
('Literatura Brasileira', 'POR252', 32, 'Escola Central SP'),
('Ciência Política', 'GEO253', 23, 'Unidade Leste SP'),
('Direito Constitucional', 'HIS254', 28, 'Centro Educacional BH'),
('Sociologia', 'ING255', 31, 'Unidade Zona Sul RJ'),
('Psicologia', 'QUI256', 32, 'Escola Central SP'),
('Antropologia', 'INF257', 25, 'Escola Oeste PR'),
('Filosofia', 'INF258', 32, 'Escola Oeste PR'),
('Ecologia', 'MAT259', 31, 'Escola Central SP'),
('Matemática Básica', 'ART260', 25, 'Unidade Zona Sul RJ'),
('Português I', 'FIS261', 27, 'Escola Técnica SSA'),
('História Geral', 'ING262', 34, 'Unidade Leste SP'),
('Geografia I', 'FIS263', 26, 'Unidade Leste SP'),
('Física Básica', 'QUI264', 27, 'Escola Central SP'),
('Química I', 'ING265', 36, 'Centro Educacional RS'),
('Biologia Celular', 'QUI266', 35, 'Unidade Leste SP'),
('Inglês Básico', 'INF267', 37, 'Instituto Norte'),
('Educação Física', 'ING268', 27, 'Instituto Sul RJ'),
('Artes Visuais', 'QUI269', 38, 'Centro Educacional RS'),
('Matemática Avançada', 'POR270', 29, 'Instituto Sul RJ'),
('Português II', 'POR271', 37, 'Escola Oeste PR'),
('História do Brasil', 'BIO272', 29, 'Instituto Norte'),
('Geografia II', 'MAT273', 27, 'Unidade Zona Sul RJ'),
('Física II', 'HIS274', 34, 'Escola Central SP'),
('Química Orgânica', 'BIO275', 40, 'Unidade Leste SP'),
('Biologia Molecular', 'ART276', 30, 'Escola Central SP'),
('Inglês Intermediário', 'INF277', 22, 'Unidade Centro PE'),
('Educação Artística', 'ING278', 34, 'Unidade Leste SP'),
('Teatro', 'QUI279', 26, 'Instituto Sul RJ'),
('Programação I', 'QUI280', 29, 'Centro Educacional RS'),
('Banco de Dados', 'HIS281', 28, 'Centro Educacional BH'),
('Redes de Computadores', 'POR282', 38, 'Centro Educacional RS'),
('Sistemas Operacionais', 'QUI283', 33, 'Unidade Centro PE'),
('Algoritmos', 'HIS284', 38, 'Centro Educacional RS'),
('Lógica de Programação', 'QUI285', 21, 'Unidade Centro PE'),
('Desenvolvimento Web', 'POR286', 40, 'Escola Oeste PR'),
('Matemática Financeira', 'ART287', 39, 'Unidade Zona Sul RJ'),
('Física Moderna', 'ING288', 30, 'Unidade Zona Sul RJ'),
('Gestão de Projetos', 'BIO289', 29, 'Escola Oeste PR'),
('Química Analítica', 'EDF290', 25, 'Escola Central SP'),
('Física Experimental', 'GEO291', 27, 'Centro Educacional BH'),
('Literatura Brasileira', 'QUI292', 25, 'Escola Oeste PR'),
('Ciência Política', 'HIS293', 40, 'Centro Educacional BH'),
('Direito Constitucional', 'POR294', 21, 'Unidade Centro PE'),
('Sociologia', 'EDF295', 36, 'Escola Central SP'),
('Psicologia', 'ING296', 32, 'Centro Educacional RS'),
('Antropologia', 'EDF297', 35, 'Unidade Centro PE'),
('Filosofia', 'POR298', 28, 'Instituto Sul RJ'),
('Ecologia', 'MAT299', 31, 'Centro Educacional RS'),
('Matemática Básica', 'HIS300', 27, 'Centro Educacional RS'),
('Português I', 'QUI301', 35, 'Centro Educacional RS'),
('História Geral', 'HIS302', 38, 'Escola Oeste PR'),
('Geografia I', 'HIS303', 22, 'Escola Oeste PR'),
('Física Básica', 'ING304', 35, 'Instituto Sul RJ'),
('Química I', 'ING305', 28, 'Instituto Sul RJ'),
('Biologia Celular', 'EDF306', 38, 'Instituto Sul RJ'),
('Inglês Básico', 'MAT307', 20, 'Unidade Centro PE'),
('Educação Física', 'ART308', 35, 'Instituto Norte'),
('Artes Visuais', 'ART309', 37, 'Instituto Norte'),
('Matemática Avançada', 'FIS310', 32, 'Centro Educacional RS'),
('Português II', 'GEO311', 26, 'Escola Oeste PR'),
('História do Brasil', 'INF312', 34, 'Unidade Centro PE'),
('Geografia II', 'FIS313', 23, 'Escola Técnica SSA'),
('Física II', 'EDF314', 20, 'Unidade Centro PE'),
('Química Orgânica', 'POR315', 37, 'Unidade Zona Sul RJ'),
('Biologia Molecular', 'BIO316', 30, 'Instituto Sul RJ'),
('Inglês Intermediário', 'MAT317', 33, 'Escola Oeste PR'),
('Educação Artística', 'EDF318', 27, 'Unidade Leste SP'),
('Teatro', 'QUI319', 23, 'Unidade Leste SP'),
('Programação I', 'QUI320', 40, 'Escola Central SP'),
('Banco de Dados', 'HIS321', 35, 'Centro Educacional RS'),
('Redes de Computadores', 'GEO322', 31, 'Centro Educacional BH'),
('Sistemas Operacionais', 'ART323', 37, 'Instituto Sul RJ'),
('Algoritmos', 'HIS324', 32, 'Escola Central SP'),
('Lógica de Programação', 'ART325', 39, 'Instituto Norte'),
('Desenvolvimento Web', 'QUI326', 30, 'Instituto Sul RJ'),
('Matemática Financeira', 'POR327', 26, 'Centro Educacional BH'),
('Física Moderna', 'BIO328', 21, 'Escola Central SP'),
('Gestão de Projetos', 'INF329', 21, 'Escola Técnica SSA'),
('Química Analítica', 'MAT330', 31, 'Unidade Zona Sul RJ'),
('Física Experimental', 'EDF331', 25, 'Escola Oeste PR'),
('Literatura Brasileira', 'GEO332', 35, 'Unidade Zona Sul RJ'),
('Ciência Política', 'INF333', 35, 'Centro Educacional RS'),
('Direito Constitucional', 'ING334', 26, 'Instituto Sul RJ'),
('Sociologia', 'MAT335', 40, 'Instituto Norte'),
('Psicologia', 'ING336', 26, 'Escola Oeste PR'),
('Antropologia', 'ART337', 21, 'Unidade Centro PE'),
('Filosofia', 'EDF338', 29, 'Unidade Leste SP'),
('Ecologia', 'EDF339', 36, 'Escola Central SP'),
('Matemática Básica', 'BIO340', 23, 'Escola Central SP'),
('Português I', 'POR341', 30, 'Escola Central SP'),
('História Geral', 'ART342', 34, 'Unidade Zona Sul RJ'),
('Geografia I', 'MAT343', 29, 'Unidade Zona Sul RJ'),
('Física Básica', 'POR344', 29, 'Escola Técnica SSA'),
('Química I', 'GEO345', 25, 'Unidade Centro PE'),
('Biologia Celular', 'QUI346', 20, 'Centro Educacional RS'),
('Inglês Básico', 'QUI347', 36, 'Escola Oeste PR'),
('Educação Física', 'BIO348', 23, 'Unidade Zona Sul RJ'),
('Artes Visuais', 'ART349', 34, 'Unidade Leste SP'),
('Matemática Avançada', 'ING350', 23, 'Escola Técnica SSA'),
('Português II', 'BIO351', 38, 'Instituto Norte'),
('História do Brasil', 'HIS352', 37, 'Centro Educacional RS'),
('Geografia II', 'MAT353', 21, 'Escola Central SP'),
('Física II', 'POR354', 21, 'Centro Educacional RS'),
('Química Orgânica', 'INF355', 20, 'Unidade Zona Sul RJ'),
('Biologia Molecular', 'MAT356', 21, 'Centro Educacional BH'),
('Inglês Intermediário', 'ART357', 39, 'Centro Educacional RS'),
('Educação Artística', 'GEO358', 32, 'Instituto Norte'),
('Teatro', 'ING359', 31, 'Instituto Sul RJ'),
('Programação I', 'HIS360', 26, 'Instituto Sul RJ'),
('Banco de Dados', 'QUI361', 31, 'Unidade Zona Sul RJ'),
('Redes de Computadores', 'INF362', 28, 'Escola Oeste PR'),
('Sistemas Operacionais', 'ART363', 29, 'Escola Oeste PR'),
('Algoritmos', 'ING364', 32, 'Instituto Norte'),
('Lógica de Programação', 'EDF365', 34, 'Instituto Norte'),
('Desenvolvimento Web', 'EDF366', 29, 'Escola Central SP'),
('Matemática Financeira', 'GEO367', 20, 'Escola Oeste PR'),
('Física Moderna', 'INF368', 28, 'Unidade Centro PE'),
('Gestão de Projetos', 'QUI369', 39, 'Unidade Centro PE'),
('Química Analítica', 'ING370', 24, 'Unidade Leste SP'),
('Física Experimental', 'HIS371', 24, 'Unidade Centro PE'),
('Literatura Brasileira', 'QUI372', 37, 'Instituto Sul RJ'),
('Ciência Política', 'BIO373', 36, 'Centro Educacional BH'),
('Direito Constitucional', 'HIS374', 39, 'Escola Central SP'),
('Sociologia', 'BIO375', 24, 'Centro Educacional RS'),
('Psicologia', 'EDF376', 27, 'Centro Educacional RS'),
('Antropologia', 'INF377', 21, 'Unidade Leste SP'),
('Filosofia', 'GEO378', 22, 'Centro Educacional BH'),
('Ecologia', 'GEO379', 20, 'Escola Central SP'),
('Matemática Básica', 'POR380', 23, 'Unidade Zona Sul RJ'),
('Português I', 'FIS381', 30, 'Escola Central SP'),
('História Geral', 'ING382', 39, 'Unidade Zona Sul RJ'),
('Geografia I', 'BIO383', 24, 'Escola Central SP'),
('Física Básica', 'POR384', 37, 'Escola Técnica SSA'),
('Química I', 'ING385', 21, 'Centro Educacional RS'),
('Biologia Celular', 'BIO386', 37, 'Centro Educacional BH'),
('Inglês Básico', 'GEO387', 31, 'Instituto Norte'),
('Educação Física', 'POR388', 39, 'Escola Central SP'),
('Artes Visuais', 'ART389', 26, 'Unidade Centro PE'),
('Matemática Avançada', 'ART390', 39, 'Escola Técnica SSA'),
('Português II', 'BIO391', 31, 'Escola Central SP'),
('História do Brasil', 'QUI392', 33, 'Centro Educacional RS'),
('Geografia II', 'ING393', 37, 'Escola Oeste PR'),
('Física II', 'FIS394', 28, 'Centro Educacional RS'),
('Química Orgânica', 'EDF395', 29, 'Instituto Norte'),
('Biologia Molecular', 'ART396', 21, 'Centro Educacional BH'),
('Inglês Intermediário', 'ART397', 26, 'Escola Central SP'),
('Educação Artística', 'INF398', 30, 'Escola Central SP'),
('Teatro', 'ART399', 27, 'Centro Educacional BH'),
('Programação I', 'POR400', 39, 'Instituto Norte'),
('Banco de Dados', 'EDF401', 26, 'Escola Central SP'),
('Redes de Computadores', 'GEO402', 31, 'Centro Educacional RS'),
('Sistemas Operacionais', 'FIS403', 33, 'Unidade Leste SP'),
('Algoritmos', 'EDF404', 21, 'Unidade Zona Sul RJ'),
('Lógica de Programação', 'POR405', 27, 'Escola Oeste PR'),
('Desenvolvimento Web', 'POR406', 38, 'Instituto Sul RJ'),
('Matemática Financeira', 'MAT407', 36, 'Escola Central SP'),
('Física Moderna', 'ART408', 31, 'Unidade Leste SP'),
('Gestão de Projetos', 'QUI409', 28, 'Unidade Zona Sul RJ'),
('Química Analítica', 'ING410', 32, 'Instituto Norte'),
('Física Experimental', 'ART411', 38, 'Escola Técnica SSA'),
('Literatura Brasileira', 'ART412', 34, 'Instituto Sul RJ'),
('Ciência Política', 'HIS413', 35, 'Instituto Sul RJ'),
('Direito Constitucional', 'MAT414', 34, 'Instituto Sul RJ'),
('Sociologia', 'ING415', 23, 'Escola Central SP'),
('Psicologia', 'EDF416', 32, 'Unidade Leste SP'),
('Antropologia', 'FIS417', 31, 'Instituto Norte'),
('Filosofia', 'HIS418', 30, 'Unidade Centro PE'),
('Ecologia', 'BIO419', 30, 'Unidade Centro PE'),
('Matemática Básica', 'POR420', 37, 'Instituto Sul RJ'),
('Português I', 'QUI421', 23, 'Escola Técnica SSA'),
('História Geral', 'FIS422', 31, 'Instituto Sul RJ'),
('Geografia I', 'QUI423', 24, 'Centro Educacional RS'),
('Física Básica', 'ART424', 35, 'Centro Educacional RS'),
('Química I', 'ING425', 34, 'Instituto Norte'),
('Biologia Celular', 'FIS426', 40, 'Escola Técnica SSA'),
('Inglês Básico', 'EDF427', 36, 'Instituto Sul RJ'),
('Educação Física', 'BIO428', 23, 'Escola Técnica SSA'),
('Artes Visuais', 'HIS429', 33, 'Instituto Norte'),
('Matemática Avançada', 'HIS430', 35, 'Escola Oeste PR'),
('Português II', 'BIO431', 30, 'Instituto Norte'),
('História do Brasil', 'ART432', 24, 'Escola Oeste PR'),
('Geografia II', 'GEO433', 32, 'Escola Técnica SSA'),
('Física II', 'POR434', 22, 'Centro Educacional RS'),
('Química Orgânica', 'MAT435', 35, 'Instituto Norte'),
('Biologia Molecular', 'GEO436', 25, 'Instituto Sul RJ'),
('Inglês Intermediário', 'MAT437', 22, 'Instituto Sul RJ'),
('Educação Artística', 'GEO438', 39, 'Escola Oeste PR'),
('Teatro', 'POR439', 30, 'Unidade Leste SP'),
('Programação I', 'MAT440', 27, 'Unidade Centro PE'),
('Banco de Dados', 'ING441', 35, 'Centro Educacional RS'),
('Redes de Computadores', 'POR442', 26, 'Instituto Sul RJ'),
('Sistemas Operacionais', 'ING443', 33, 'Unidade Leste SP'),
('Algoritmos', 'POR444', 38, 'Escola Técnica SSA'),
('Lógica de Programação', 'FIS445', 21, 'Escola Técnica SSA'),
('Desenvolvimento Web', 'POR446', 33, 'Instituto Norte'),
('Matemática Financeira', 'BIO447', 30, 'Centro Educacional BH'),
('Física Moderna', 'ART448', 21, 'Escola Oeste PR'),
('Gestão de Projetos', 'ART449', 34, 'Unidade Leste SP'),
('Química Analítica', 'QUI450', 28, 'Centro Educacional RS'),
('Física Experimental', 'EDF451', 32, 'Escola Técnica SSA'),
('Literatura Brasileira', 'FIS452', 26, 'Unidade Centro PE'),
('Ciência Política', 'ART453', 31, 'Unidade Zona Sul RJ'),
('Direito Constitucional', 'FIS454', 38, 'Unidade Centro PE'),
('Sociologia', 'ING455', 32, 'Centro Educacional RS'),
('Psicologia', 'ART456', 20, 'Unidade Centro PE'),
('Antropologia', 'MAT457', 36, 'Unidade Centro PE'),
('Filosofia', 'EDF458', 34, 'Instituto Sul RJ'),
('Ecologia', 'BIO459', 31, 'Instituto Sul RJ'),
('Matemática Básica', 'MAT460', 33, 'Instituto Sul RJ'),
('Português I', 'MAT461', 22, 'Escola Oeste PR'),
('História Geral', 'HIS462', 34, 'Unidade Leste SP'),
('Geografia I', 'ING463', 31, 'Unidade Leste SP'),
('Física Básica', 'GEO464', 23, 'Centro Educacional RS'),
('Química I', 'EDF465', 28, 'Escola Oeste PR'),
('Biologia Celular', 'ING466', 31, 'Escola Oeste PR'),
('Inglês Básico', 'MAT467', 32, 'Escola Central SP'),
('Educação Física', 'BIO468', 24, 'Unidade Leste SP'),
('Artes Visuais', 'INF469', 40, 'Centro Educacional RS'),
('Matemática Avançada', 'MAT470', 32, 'Centro Educacional BH'),
('Português II', 'GEO471', 36, 'Unidade Centro PE'),
('História do Brasil', 'INF472', 24, 'Unidade Leste SP'),
('Geografia II', 'EDF473', 28, 'Centro Educacional RS'),
('Física II', 'HIS474', 29, 'Instituto Sul RJ'),
('Química Orgânica', 'BIO475', 23, 'Escola Técnica SSA'),
('Biologia Molecular', 'BIO476', 22, 'Unidade Centro PE'),
('Inglês Intermediário', 'BIO477', 21, 'Centro Educacional RS'),
('Educação Artística', 'ART478', 23, 'Unidade Zona Sul RJ'),
('Teatro', 'POR479', 34, 'Escola Técnica SSA'),
('Programação I', 'ART480', 21, 'Escola Central SP'),
('Banco de Dados', 'BIO481', 25, 'Escola Técnica SSA'),
('Redes de Computadores', 'QUI482', 38, 'Escola Técnica SSA'),
('Sistemas Operacionais', 'FIS483', 31, 'Unidade Leste SP'),
('Algoritmos', 'POR484', 20, 'Unidade Zona Sul RJ'),
('Lógica de Programação', 'BIO485', 28, 'Unidade Zona Sul RJ'),
('Desenvolvimento Web', 'POR486', 32, 'Unidade Zona Sul RJ'),
('Matemática Financeira', 'ING487', 27, 'Instituto Norte'),
('Física Moderna', 'QUI488', 39, 'Unidade Centro PE'),
('Gestão de Projetos', 'MAT489', 35, 'Instituto Norte'),
('Química Analítica', 'ING490', 35, 'Unidade Centro PE'),
('Física Experimental', 'ART491', 32, 'Escola Central SP'),
('Literatura Brasileira', 'EDF492', 21, 'Instituto Sul RJ'),
('Ciência Política', 'ING493', 31, 'Unidade Leste SP'),
('Direito Constitucional', 'MAT494', 26, 'Escola Central SP'),
('Sociologia', 'BIO495', 22, 'Escola Técnica SSA'),
('Psicologia', 'ING496', 23, 'Unidade Centro PE'),
('Antropologia', 'EDF497', 24, 'Centro Educacional RS'),
('Filosofia', 'QUI498', 23, 'Escola Central SP'),
('Ecologia', 'HIS499', 38, 'Unidade Leste SP'),
('Matemática Básica', 'GEO500', 30, 'Centro Educacional RS'),
('Português I', 'ART501', 32, 'Escola Central SP'),
('História Geral', 'ING502', 39, 'Unidade Zona Sul RJ'),
('Geografia I', 'BIO503', 40, 'Instituto Sul RJ'),
('Física Básica', 'ING504', 40, 'Instituto Norte'),
('Química I', 'MAT505', 26, 'Centro Educacional BH'),
('Biologia Celular', 'QUI506', 20, 'Escola Central SP'),
('Inglês Básico', 'GEO507', 35, 'Unidade Zona Sul RJ'),
('Educação Física', 'ING508', 40, 'Escola Técnica SSA'),
('Artes Visuais', 'GEO509', 33, 'Instituto Norte'),
('Matemática Avançada', 'GEO510', 37, 'Instituto Norte'),
('Português II', 'QUI511', 21, 'Unidade Centro PE'),
('História do Brasil', 'INF512', 29, 'Instituto Sul RJ'),
('Geografia II', 'EDF513', 24, 'Unidade Leste SP'),
('Física II', 'ING514', 27, 'Instituto Norte'),
('Química Orgânica', 'ING515', 40, 'Unidade Centro PE'),
('Biologia Molecular', 'QUI516', 32, 'Unidade Leste SP'),
('Inglês Intermediário', 'BIO517', 26, 'Centro Educacional RS'),
('Educação Artística', 'ART518', 23, 'Centro Educacional RS'),
('Teatro', 'EDF519', 28, 'Unidade Leste SP'),
('Programação I', 'BIO520', 36, 'Unidade Zona Sul RJ'),
('Banco de Dados', 'INF521', 34, 'Escola Oeste PR'),
('Redes de Computadores', 'HIS522', 38, 'Instituto Norte'),
('Sistemas Operacionais', 'GEO523', 25, 'Escola Oeste PR'),
('Algoritmos', 'EDF524', 29, 'Instituto Norte'),
('Lógica de Programação', 'EDF525', 23, 'Centro Educacional RS'),
('Desenvolvimento Web', 'BIO526', 27, 'Instituto Norte'),
('Matemática Financeira', 'FIS527', 37, 'Escola Central SP'),
('Física Moderna', 'GEO528', 31, 'Centro Educacional BH'),
('Gestão de Projetos', 'GEO529', 24, 'Escola Oeste PR'),
('Química Analítica', 'GEO530', 20, 'Escola Central SP'),
('Física Experimental', 'ART531', 21, 'Centro Educacional BH'),
('Literatura Brasileira', 'EDF532', 29, 'Instituto Norte'),
('Ciência Política', 'BIO533', 33, 'Unidade Zona Sul RJ'),
('Direito Constitucional', 'MAT534', 23, 'Escola Central SP'),
('Sociologia', 'EDF535', 39, 'Unidade Leste SP'),
('Psicologia', 'HIS536', 26, 'Unidade Zona Sul RJ'),
('Antropologia', 'BIO537', 35, 'Unidade Zona Sul RJ'),
('Filosofia', 'BIO538', 36, 'Unidade Leste SP'),
('Ecologia', 'MAT539', 28, 'Instituto Sul RJ'),
('Matemática Básica', 'GEO540', 24, 'Escola Oeste PR'),
('Português I', 'EDF541', 24, 'Instituto Sul RJ'),
('História Geral', 'ART542', 22, 'Instituto Sul RJ'),
('Geografia I', 'QUI543', 34, 'Escola Oeste PR'),
('Física Básica', 'MAT544', 25, 'Instituto Norte'),
('Química I', 'MAT545', 24, 'Centro Educacional BH'),
('Biologia Celular', 'POR546', 28, 'Escola Oeste PR'),
('Inglês Básico', 'EDF547', 33, 'Escola Central SP'),
('Educação Física', 'POR548', 33, 'Centro Educacional RS'),
('Artes Visuais', 'POR549', 32, 'Unidade Zona Sul RJ'),
('Matemática Avançada', 'GEO550', 25, 'Centro Educacional RS'),
('Português II', 'BIO551', 24, 'Instituto Sul RJ'),
('História do Brasil', 'INF552', 26, 'Escola Central SP'),
('Geografia II', 'EDF553', 26, 'Unidade Centro PE'),
('Física II', 'FIS554', 35, 'Unidade Centro PE'),
('Química Orgânica', 'GEO555', 28, 'Escola Oeste PR'),
('Biologia Molecular', 'QUI556', 38, 'Unidade Leste SP'),
('Inglês Intermediário', 'INF557', 25, 'Unidade Zona Sul RJ'),
('Educação Artística', 'FIS558', 31, 'Escola Técnica SSA'),
('Teatro', 'QUI559', 21, 'Unidade Zona Sul RJ'),
('Programação I', 'EDF560', 37, 'Centro Educacional BH'),
('Banco de Dados', 'INF561', 35, 'Unidade Zona Sul RJ'),
('Redes de Computadores', 'INF562', 33, 'Escola Técnica SSA'),
('Sistemas Operacionais', 'QUI563', 39, 'Instituto Norte'),
('Algoritmos', 'HIS564', 39, 'Unidade Centro PE'),
('Lógica de Programação', 'QUI565', 31, 'Escola Oeste PR'),
('Desenvolvimento Web', 'BIO566', 39, 'Escola Técnica SSA'),
('Matemática Financeira', 'ING567', 22, 'Centro Educacional BH'),
('Física Moderna', 'MAT568', 29, 'Escola Oeste PR'),
('Gestão de Projetos', 'ING569', 34, 'Escola Oeste PR'),
('Química Analítica', 'POR570', 33, 'Escola Técnica SSA'),
('Física Experimental', 'ING571', 22, 'Escola Oeste PR'),
('Literatura Brasileira', 'FIS572', 39, 'Instituto Norte'),
('Ciência Política', 'FIS573', 22, 'Escola Central SP'),
('Direito Constitucional', 'QUI574', 27, 'Unidade Leste SP'),
('Sociologia', 'FIS575', 32, 'Centro Educacional RS'),
('Psicologia', 'FIS576', 38, 'Unidade Leste SP'),
('Antropologia', 'HIS577', 26, 'Escola Oeste PR'),
('Filosofia', 'POR578', 23, 'Instituto Norte'),
('Ecologia', 'BIO579', 33, 'Escola Central SP'),
('Matemática Básica', 'HIS580', 28, 'Unidade Leste SP'),
('Português I', 'FIS581', 24, 'Unidade Leste SP'),
('História Geral', 'MAT582', 24, 'Unidade Leste SP'),
('Geografia I', 'ING583', 26, 'Escola Oeste PR'),
('Física Básica', 'BIO584', 21, 'Escola Técnica SSA'),
('Química I', 'GEO585', 39, 'Unidade Leste SP'),
('Biologia Celular', 'BIO586', 26, 'Unidade Leste SP'),
('Inglês Básico', 'GEO587', 28, 'Unidade Zona Sul RJ'),
('Educação Física', 'MAT588', 26, 'Instituto Sul RJ'),
('Artes Visuais', 'POR589', 30, 'Escola Oeste PR'),
('Matemática Avançada', 'MAT590', 35, 'Instituto Sul RJ'),
('Português II', 'GEO591', 33, 'Centro Educacional RS'),
('História do Brasil', 'FIS592', 21, 'Unidade Centro PE'),
('Geografia II', 'HIS593', 28, 'Unidade Leste SP'),
('Física II', 'MAT594', 38, 'Centro Educacional BH'),
('Química Orgânica', 'BIO595', 39, 'Centro Educacional BH'),
('Biologia Molecular', 'POR596', 30, 'Centro Educacional BH'),
('Inglês Intermediário', 'ART597', 39, 'Unidade Centro PE'),
('Educação Artística', 'ING598', 22, 'Unidade Leste SP'),
('Teatro', 'HIS599', 28, 'Unidade Zona Sul RJ');