INSERT INTO INFRADISCIPLINA (
    Codigo_Disc, Tipo_Infra
) VALUES
('FIS100', 'Sala de Estudo Individual'),
('FIS100', 'Oficina de Mecânica'),
('FIS100', 'Sala dos Professores'),
('POR101', 'Laboratório de História'),
('POR101', 'Laboratório de Línguas'),
('POR101', 'Laboratório de Análises Clínicas'),
('ART102', 'Sala de Projeção'),
('ART102', 'Cantina'),
('ART102', 'Sala de Empreendedorismo'),
('QUI103', 'Laboratório de Meio Ambiente'),
('QUI103', 'Laboratório de Línguas'),
('QUI103', 'Laboratório de Engenharia Química'),
('QUI104', 'Laboratório de Robótica'),
('QUI104', 'Sala de Defesas de TCC'),
('QUI104', 'Sala de Informática'),
('GEO105', 'Sala de Leitura'),
('GEO105', 'Sala de Empreendedorismo'),
('GEO105', 'Laboratório de Nutrição'),
('MAT106', 'Sala de Atendimento Psicológico'),
('MAT106', 'Laboratório de Design Gráfico'),
('MAT106', 'Laboratório de Análises Clínicas'),
('QUI107', 'Estúdio de Gravação'),
('QUI107', 'Sala de Estudos Interdisciplinares'),
('QUI107', 'Sala de Atendimento Psicológico'),
('ART108', 'Sala de Atendimento Psicológico'),
('ART108', 'Refeitório'),
('ART108', 'Laboratório de Análise de Dados'),
('EDF109', 'Sala de Leitura'),
('EDF109', 'Sala de Impressão 3D'),
('EDF109', 'Sala de Estudos Interdisciplinares'),
('BIO110', 'Sala de Atendimento Psicológico'),
('BIO110', 'Laboratório de Línguas'),
('BIO110', 'Sala de Música'),
('FIS111', 'Sala de Leitura'),
('FIS111', 'Laboratório de Análise de Dados'),
('FIS111', 'Laboratório de Análises Clínicas'),
('ING112', 'Sala de Empreendedorismo'),
('ING112', 'Sala de Atendimento Psicológico'),
('ING112', 'Sala de Leitura'),
('EDF113', 'Sala de Modelagem 3D'),
('EDF113', 'Laboratório de Produção de Vídeo'),
('EDF113', 'Sala de Coordenação'),
('GEO114', 'Laboratório de Robótica'),
('GEO114', 'Laboratório de Engenharia'),
('GEO114', 'Sala de Música'),
('ART115', 'Laboratório de Biologia'),
('ART115', 'Sala de Leitura'),
('ART115', 'Sala de Artes'),
('ART116', 'Laboratório de Redes'),
('ART116', 'Sala de Defesas de TCC'),
('ART116', 'Laboratório de Biologia'),
('ART117', 'Laboratório de Realidade Virtual'),
('ART117', 'Laboratório de Automação'),
('ART117', 'Sala de Artes'),
('HIS118', 'Refeitório'),
('HIS118', 'Laboratório de Produção de Vídeo'),
('HIS118', 'Laboratório de Fotografia'),
('INF119', 'Laboratório de Engenharia Química'),
('INF119', 'Sala de Música'),
('INF119', 'Laboratório de Programação'),
('HIS120', 'Laboratório de Construção Civil'),
('HIS120', 'Sala de Estudo Individual'),
('HIS120', 'Cantina'),
('GEO121', 'Sala de Coordenação'),
('GEO121', 'Sala de Empreendedorismo'),
('GEO121', 'Sala de Atendimento Psicológico'),
('ING122', 'Sala de Artes'),
('ING122', 'Sala de Coordenação'),
('ING122', 'Sala de Desenvolvimento de Software'),
('MAT123', 'Laboratório de Engenharia'),
('MAT123', 'Sala dos Professores'),
('MAT123', 'Laboratório de Produção de Vídeo'),
('INF124', 'Sala de Música'),
('INF124', 'Quadra Poliesportiva'),
('INF124', 'Laboratório de Inteligência Artificial'),
('FIS125', 'Auditório'),
('FIS125', 'Laboratório de Engenharia'),
('FIS125', 'Laboratório de Física'),
('BIO126', 'Laboratório de Construção Civil'),
('BIO126', 'Laboratório de Design Gráfico'),
('BIO126', 'Refeitório'),
('QUI127', 'Sala de Informática'),
('QUI127', 'Sala de Desenvolvimento de Software'),
('QUI127', 'Sala de Defesas de TCC'),
('FIS128', 'Auditório'),
('FIS128', 'Laboratório de Redes'),
('FIS128', 'Sala dos Professores'),
('FIS129', 'Laboratório de Meio Ambiente'),
('FIS129', 'Laboratório de Línguas'),
('FIS129', 'Laboratório de Eletrônica'),
('ING130', 'Sala de Informática'),
('ING130', 'Laboratório de Construção Civil'),
('ING130', 'Sala de Desenvolvimento de Software'),
('QUI131', 'Cantina'),
('QUI131', 'Laboratório de Análise de Dados'),
('QUI131', 'Laboratório de Geografia'),
('BIO132', 'Laboratório de Eletrônica'),
('BIO132', 'Laboratório de Inteligência Artificial'),
('BIO132', 'Laboratório de Física'),
('POR133', 'Laboratório de História'),
('POR133', 'Sala de Estudo em Grupo'),
('POR133', 'Laboratório de Línguas'),
('ING134', 'Sala de Informática'),
('ING134', 'Laboratório de Construção Civil'),
('ING134', 'Laboratório de Fotografia'),
('INF135', 'Auditório'),
('INF135', 'Laboratório de Design Gráfico'),
('INF135', 'Sala de Jogos Educativos'),
('ART136', 'Laboratório de Nutrição'),
('ART136', 'Sala de Artes'),
('ART136', 'Sala de Leitura'),
('GEO137', 'Cantina'),
('GEO137', 'Laboratório de Nutrição'),
('GEO137', 'Sala de Impressão 3D'),
('ART138', 'Laboratório de Ciência dos Materiais'),
('ART138', 'Laboratório de Química'),
('ART138', 'Laboratório de Análise de Dados'),
('BIO139', 'Laboratório de Design Gráfico'),
('BIO139', 'Sala de Jogos Educativos'),
('BIO139', 'Estúdio de Gravação'),
('POR140', 'Oficina de Mecânica'),
('POR140', 'Sala de Modelagem 3D'),
('POR140', 'Laboratório de História'),
('INF141', 'Laboratório de Geografia'),
('INF141', 'Laboratório de Ciência dos Materiais'),
('INF141', 'Laboratório de Produção de Vídeo'),
('EDF142', 'Sala de Estudo em Grupo'),
('EDF142', 'Laboratório de Microbiologia'),
('EDF142', 'Laboratório de Geografia'),
('EDF143', 'Sala de Impressão 3D'),
('EDF143', 'Laboratório de Análises Clínicas'),
('EDF143', 'Quadra Poliesportiva'),
('HIS144', 'Laboratório de Física'),
('HIS144', 'Sala de Projeção'),
('HIS144', 'Laboratório de Eletrônica'),
('MAT145', 'Laboratório de Nutrição'),
('MAT145', 'Sala de Coordenação'),
('MAT145', 'Sala de Impressão 3D'),
('POR146', 'Laboratório de Eletrônica'),
('POR146', 'Laboratório de Análise de Dados'),
('POR146', 'Laboratório de Produção de Vídeo'),
('GEO147', 'Laboratório de Geografia'),
('GEO147', 'Sala de Estudos Interdisciplinares'),
('GEO147', 'Laboratório de Eletrônica'),
('FIS148', 'Laboratório de Engenharia'),
('FIS148', 'Laboratório de Meio Ambiente'),
('FIS148', 'Laboratório de Análise de Dados'),
('FIS149', 'Sala de Desenvolvimento de Software'),
('FIS149', 'Biblioteca'),
('FIS149', 'Estúdio de Gravação'),
('ART150', 'Laboratório de Design Gráfico'),
('ART150', 'Laboratório de Física'),
('ART150', 'Laboratório de Matemática'),
('POR151', 'Laboratório de Análises Clínicas'),
('POR151', 'Cantina'),
('POR151', 'Sala de Estudo em Grupo'),
('MAT152', 'Laboratório de Microbiologia'),
('MAT152', 'Sala de Estudo em Grupo'),
('MAT152', 'Sala de Atendimento Psicológico'),
('BIO153', 'Sala de Artes'),
('BIO153', 'Oficina de Mecânica'),
('BIO153', 'Laboratório de Análise de Dados'),
('MAT154', 'Refeitório'),
('MAT154', 'Laboratório de Robótica'),
('MAT154', 'Sala de Estudo em Grupo'),
('MAT155', 'Refeitório'),
('MAT155', 'Laboratório de Matemática'),
('MAT155', 'Laboratório de Robótica'),
('FIS156', 'Sala de Estudos Interdisciplinares'),
('FIS156', 'Oficina de Mecânica'),
('FIS156', 'Sala de Empreendedorismo'),
('ING157', 'Sala de Coordenação'),
('ING157', 'Laboratório de Línguas'),
('ING157', 'Laboratório de Design Gráfico'),
('QUI158', 'Laboratório de Análise de Dados'),
('QUI158', 'Laboratório de Línguas'),
('QUI158', 'Laboratório de Realidade Virtual'),
('MAT159', 'Refeitório'),
('MAT159', 'Laboratório de Química'),
('MAT159', 'Laboratório de Design Gráfico'),
('INF160', 'Laboratório de Biologia'),
('INF160', 'Sala de Impressão 3D'),
('INF160', 'Laboratório de Programação'),
('FIS161', 'Sala de Atendimento Psicológico'),
('FIS161', 'Laboratório de Produção de Vídeo'),
('FIS161', 'Sala de Informática'),
('POR162', 'Laboratório de Produção de Vídeo'),
('POR162', 'Laboratório de Programação'),
('POR162', 'Laboratório de Construção Civil'),
('MAT163', 'Laboratório de Engenharia Química'),
('MAT163', 'Laboratório de Biologia'),
('MAT163', 'Sala de Atendimento Psicológico'),
('GEO164', 'Laboratório de Meio Ambiente'),
('GEO164', 'Laboratório de Produção de Vídeo'),
('GEO164', 'Laboratório de Eletrônica'),
('FIS165', 'Sala dos Professores'),
('FIS165', 'Sala de Leitura'),
('FIS165', 'Sala de Artes'),
('GEO166', 'Laboratório de Engenharia Química'),
('GEO166', 'Laboratório de Construção Civil'),
('GEO166', 'Laboratório de Meio Ambiente'),
('POR167', 'Laboratório de Redes'),
('POR167', 'Laboratório de Fotografia'),
('POR167', 'Laboratório de História'),
('HIS168', 'Sala de Artes'),
('HIS168', 'Sala de Estudo Individual'),
('HIS168', 'Laboratório de Produção de Vídeo'),
('FIS169', 'Laboratório de Nutrição'),
('FIS169', 'Laboratório de Produção de Vídeo'),
('FIS169', 'Laboratório de Matemática'),
('EDF170', 'Laboratório de Realidade Virtual'),
('EDF170', 'Laboratório de Meio Ambiente'),
('EDF170', 'Sala dos Professores'),
('POR171', 'Sala de Coordenação'),
('POR171', 'Sala de Projeção'),
('POR171', 'Laboratório de Programação'),
('HIS172', 'Laboratório de Análises Clínicas'),
('HIS172', 'Sala de Jogos Educativos'),
('HIS172', 'Laboratório de Eletrônica'),
('GEO173', 'Sala dos Professores'),
('GEO173', 'Sala de Desenvolvimento de Software'),
('GEO173', 'Laboratório de Geografia'),
('ART174', 'Sala de Jogos Educativos'),
('ART174', 'Sala de Coordenação'),
('ART174', 'Laboratório de Robótica'),
('HIS175', 'Laboratório de Química'),
('HIS175', 'Laboratório de Redes'),
('HIS175', 'Laboratório de Engenharia Química'),
('EDF176', 'Sala de Coordenação'),
('EDF176', 'Oficina de Mecânica'),
('EDF176', 'Sala de Impressão 3D'),
('INF177', 'Sala de Defesas de TCC'),
('INF177', 'Laboratório de Geografia'),
('INF177', 'Laboratório de Construção Civil'),
('EDF178', 'Laboratório de Produção de Vídeo'),
('EDF178', 'Cantina'),
('EDF178', 'Sala de Desenvolvimento de Software'),
('FIS179', 'Sala de Informática'),
('FIS179', 'Sala de Defesas de TCC'),
('FIS179', 'Laboratório de Engenharia'),
('BIO180', 'Laboratório de Química'),
('BIO180', 'Sala de Coordenação'),
('BIO180', 'Laboratório de Realidade Virtual'),
('FIS181', 'Biblioteca'),
('FIS181', 'Sala de Estudo em Grupo'),
('FIS181', 'Sala de Estudos Interdisciplinares'),
('INF182', 'Sala dos Professores'),
('INF182', 'Sala de Defesas de TCC'),
('INF182', 'Laboratório de Química'),
('ING183', 'Sala de Artes'),
('ING183', 'Laboratório de Nutrição'),
('ING183', 'Sala de Impressão 3D'),
('EDF184', 'Sala de Projeção'),
('EDF184', 'Laboratório de Química'),
('EDF184', 'Laboratório de Meio Ambiente'),
('MAT185', 'Laboratório de Construção Civil'),
('MAT185', 'Sala de Defesas de TCC'),
('MAT185', 'Laboratório de Design Gráfico'),
('QUI186', 'Laboratório de Fotografia'),
('QUI186', 'Laboratório de Realidade Virtual'),
('QUI186', 'Oficina de Mecânica'),
('EDF187', 'Sala de Modelagem 3D'),
('EDF187', 'Biblioteca'),
('EDF187', 'Refeitório'),
('FIS188', 'Laboratório de Física'),
('FIS188', 'Refeitório'),
('FIS188', 'Laboratório de Análise de Dados'),
('MAT189', 'Laboratório de Meio Ambiente'),
('MAT189', 'Biblioteca'),
('MAT189', 'Laboratório de Microbiologia'),
('MAT190', 'Laboratório de Automação'),
('MAT190', 'Estúdio de Gravação'),
('MAT190', 'Sala de Artes'),
('QUI191', 'Laboratório de Engenharia Química'),
('QUI191', 'Sala de Desenvolvimento de Software'),
('QUI191', 'Oficina de Mecânica'),
('EDF192', 'Laboratório de Nutrição'),
('EDF192', 'Laboratório de Automação'),
('EDF192', 'Laboratório de Engenharia Química'),
('INF193', 'Sala de Artes'),
('INF193', 'Laboratório de Construção Civil'),
('INF193', 'Biblioteca'),
('GEO194', 'Sala de Estudos Interdisciplinares'),
('GEO194', 'Quadra Poliesportiva'),
('GEO194', 'Laboratório de Automação'),
('EDF195', 'Laboratório de Nutrição'),
('EDF195', 'Laboratório de Química'),
('EDF195', 'Laboratório de Robótica'),
('BIO196', 'Biblioteca'),
('BIO196', 'Sala de Estudo Individual'),
('BIO196', 'Laboratório de Geografia'),
('BIO197', 'Sala de Coordenação'),
('BIO197', 'Laboratório de Física'),
('BIO197', 'Refeitório'),
('POR198', 'Laboratório de Design Gráfico'),
('POR198', 'Laboratório de Química'),
('POR198', 'Refeitório'),
('HIS199', 'Refeitório'),
('HIS199', 'Laboratório de Línguas'),
('HIS199', 'Sala de Defesas de TCC'),
('MAT200', 'Sala de Modelagem 3D'),
('MAT200', 'Laboratório de Química'),
('MAT200', 'Sala de Música'),
('INF201', 'Laboratório de Fotografia'),
('INF201', 'Sala de Jogos Educativos'),
('INF201', 'Sala de Projeção'),
('EDF202', 'Sala de Estudo em Grupo'),
('EDF202', 'Laboratório de Nutrição'),
('EDF202', 'Laboratório de Biologia'),
('ART203', 'Laboratório de Geografia'),
('ART203', 'Oficina de Mecânica'),
('ART203', 'Laboratório de Meio Ambiente'),
('ING204', 'Sala dos Professores'),
('ING204', 'Laboratório de Robótica'),
('ING204', 'Laboratório de História'),
('HIS205', 'Biblioteca'),
('HIS205', 'Laboratório de Produção de Vídeo'),
('HIS205', 'Laboratório de Matemática'),
('QUI206', 'Laboratório de Automação'),
('QUI206', 'Laboratório de Realidade Virtual'),
('QUI206', 'Sala de Defesas de TCC'),
('HIS207', 'Laboratório de Inteligência Artificial'),
('HIS207', 'Cantina'),
('HIS207', 'Sala de Estudo em Grupo'),
('MAT208', 'Estúdio de Gravação'),
('MAT208', 'Laboratório de Inteligência Artificial'),
('MAT208', 'Laboratório de Análise de Dados'),
('QUI209', 'Laboratório de Engenharia'),
('QUI209', 'Laboratório de Fotografia'),
('QUI209', 'Laboratório de Matemática'),
('ART210', 'Sala de Impressão 3D'),
('ART210', 'Sala de Artes'),
('ART210', 'Sala de Estudo Individual'),
('ART211', 'Refeitório'),
('ART211', 'Laboratório de Eletrônica'),
('ART211', 'Laboratório de Engenharia Química'),
('GEO212', 'Laboratório de Robótica'),
('GEO212', 'Laboratório de Análises Clínicas'),
('GEO212', 'Sala de Empreendedorismo'),
('ING213', 'Laboratório de Inteligência Artificial'),
('ING213', 'Cantina'),
('ING213', 'Oficina de Mecânica'),
('POR214', 'Laboratório de Fotografia'),
('POR214', 'Sala de Desenvolvimento de Software'),
('POR214', 'Quadra Poliesportiva'),
('POR215', 'Laboratório de Microbiologia'),
('POR215', 'Sala de Estudo Individual'),
('POR215', 'Laboratório de Inteligência Artificial'),
('EDF216', 'Sala de Modelagem 3D'),
('EDF216', 'Sala de Artes'),
('EDF216', 'Laboratório de Robótica'),
('POR217', 'Sala de Empreendedorismo'),
('POR217', 'Laboratório de Matemática'),
('POR217', 'Laboratório de Análise de Dados'),
('GEO218', 'Laboratório de Microbiologia'),
('GEO218', 'Sala de Leitura'),
('GEO218', 'Laboratório de Línguas'),
('POR219', 'Laboratório de Biologia'),
('POR219', 'Laboratório de História'),
('POR219', 'Sala de Defesas de TCC'),
('ART220', 'Sala de Estudo em Grupo'),
('ART220', 'Biblioteca'),
('ART220', 'Sala de Estudos Interdisciplinares'),
('HIS221', 'Cantina'),
('HIS221', 'Biblioteca'),
('HIS221', 'Quadra Poliesportiva'),
('GEO222', 'Laboratório de Fotografia'),
('GEO222', 'Sala de Coordenação'),
('GEO222', 'Laboratório de Realidade Virtual'),
('POR223', 'Sala de Desenvolvimento de Software'),
('POR223', 'Biblioteca'),
('POR223', 'Laboratório de Ciência dos Materiais'),
('MAT224', 'Laboratório de Nutrição'),
('MAT224', 'Laboratório de Matemática'),
('MAT224', 'Sala de Leitura'),
('FIS225', 'Estúdio de Gravação'),
('FIS225', 'Quadra Poliesportiva'),
('FIS225', 'Laboratório de Línguas'),
('EDF226', 'Laboratório de Línguas'),
('EDF226', 'Sala de Estudo Individual'),
('EDF226', 'Laboratório de História'),
('ING227', 'Sala de Artes'),
('ING227', 'Laboratório de Redes'),
('ING227', 'Sala de Estudo Individual'),
('HIS228', 'Sala de Impressão 3D'),
('HIS228', 'Sala dos Professores'),
('HIS228', 'Sala de Artes'),
('QUI229', 'Laboratório de Programação'),
('QUI229', 'Laboratório de Engenharia Química'),
('QUI229', 'Laboratório de Matemática'),
('GEO230', 'Laboratório de Produção de Vídeo'),
('GEO230', 'Laboratório de Ciência dos Materiais'),
('GEO230', 'Sala de Atendimento Psicológico'),
('EDF231', 'Laboratório de Línguas'),
('EDF231', 'Sala de Modelagem 3D'),
('EDF231', 'Laboratório de Nutrição'),
('EDF232', 'Sala de Artes'),
('EDF232', 'Biblioteca'),
('EDF232', 'Refeitório'),
('FIS233', 'Sala de Jogos Educativos'),
('FIS233', 'Laboratório de Meio Ambiente'),
('FIS233', 'Laboratório de Engenharia'),
('ING234', 'Laboratório de Análises Clínicas'),
('ING234', 'Biblioteca'),
('ING234', 'Laboratório de Realidade Virtual'),
('HIS235', 'Laboratório de Engenharia'),
('HIS235', 'Laboratório de Biologia'),
('HIS235', 'Laboratório de Nutrição'),
('GEO236', 'Sala de Defesas de TCC'),
('GEO236', 'Sala de Estudo Individual'),
('GEO236', 'Sala de Modelagem 3D'),
('HIS237', 'Laboratório de Automação'),
('HIS237', 'Sala de Estudos Interdisciplinares'),
('HIS237', 'Laboratório de Línguas'),
('HIS238', 'Sala de Estudo em Grupo'),
('HIS238', 'Laboratório de Química'),
('HIS238', 'Sala de Atendimento Psicológico'),
('BIO239', 'Sala de Jogos Educativos'),
('BIO239', 'Laboratório de Engenharia Química'),
('BIO239', 'Laboratório de Análises Clínicas'),
('HIS240', 'Sala de Informática'),
('HIS240', 'Estúdio de Gravação'),
('HIS240', 'Cantina'),
('GEO241', 'Refeitório'),
('GEO241', 'Laboratório de Microbiologia'),
('GEO241', 'Laboratório de Construção Civil'),
('ART242', 'Laboratório de Análise de Dados'),
('ART242', 'Laboratório de Construção Civil'),
('ART242', 'Laboratório de Matemática'),
('BIO243', 'Laboratório de Realidade Virtual'),
('BIO243', 'Laboratório de Construção Civil'),
('BIO243', 'Laboratório de Microbiologia'),
('POR244', 'Laboratório de Redes'),
('POR244', 'Laboratório de Engenharia Química'),
('POR244', 'Laboratório de Automação'),
('FIS245', 'Sala de Estudo Individual'),
('FIS245', 'Sala de Projeção'),
('FIS245', 'Laboratório de Nutrição'),
('BIO246', 'Sala de Empreendedorismo'),
('BIO246', 'Sala de Jogos Educativos'),
('BIO246', 'Laboratório de Design Gráfico'),
('INF247', 'Laboratório de Análises Clínicas'),
('INF247', 'Laboratório de Matemática'),
('INF247', 'Biblioteca'),
('INF248', 'Laboratório de Análises Clínicas'),
('INF248', 'Sala de Atendimento Psicológico'),
('INF248', 'Laboratório de Matemática'),
('GEO249', 'Sala de Coordenação'),
('GEO249', 'Laboratório de Línguas'),
('GEO249', 'Sala de Estudos Interdisciplinares'),
('EDF250', 'Laboratório de Meio Ambiente'),
('EDF250', 'Laboratório de Línguas'),
('EDF250', 'Auditório'),
('INF251', 'Sala de Defesas de TCC'),
('INF251', 'Sala de Coordenação'),
('INF251', 'Cantina'),
('POR252', 'Sala de Estudo em Grupo'),
('POR252', 'Sala de Música'),
('POR252', 'Laboratório de Engenharia Química'),
('GEO253', 'Laboratório de Microbiologia'),
('GEO253', 'Laboratório de Redes'),
('GEO253', 'Laboratório de História'),
('HIS254', 'Sala dos Professores'),
('HIS254', 'Laboratório de Ciência dos Materiais'),
('HIS254', 'Sala de Projeção'),
('ING255', 'Laboratório de Línguas'),
('ING255', 'Laboratório de Eletrônica'),
('ING255', 'Laboratório de Engenharia'),
('QUI256', 'Sala de Música'),
('QUI256', 'Sala de Estudos Interdisciplinares'),
('QUI256', 'Laboratório de Biologia'),
('INF257', 'Laboratório de Programação'),
('INF257', 'Sala de Estudo Individual'),
('INF257', 'Sala de Defesas de TCC'),
('INF258', 'Sala de Coordenação'),
('INF258', 'Sala de Leitura'),
('INF258', 'Laboratório de Robótica'),
('MAT259', 'Sala de Impressão 3D'),
('MAT259', 'Sala de Jogos Educativos'),
('MAT259', 'Laboratório de Produção de Vídeo'),
('ART260', 'Laboratório de Design Gráfico'),
('ART260', 'Laboratório de Nutrição'),
('ART260', 'Sala de Defesas de TCC'),
('FIS261', 'Biblioteca'),
('FIS261', 'Laboratório de Eletrônica'),
('FIS261', 'Sala de Impressão 3D'),
('ING262', 'Laboratório de História'),
('ING262', 'Laboratório de Inteligência Artificial'),
('ING262', 'Laboratório de Produção de Vídeo'),
('FIS263', 'Oficina de Mecânica'),
('FIS263', 'Laboratório de Meio Ambiente'),
('FIS263', 'Laboratório de Realidade Virtual'),
('QUI264', 'Sala dos Professores'),
('QUI264', 'Sala de Leitura'),
('QUI264', 'Laboratório de Programação'),
('ING265', 'Sala de Atendimento Psicológico'),
('ING265', 'Laboratório de Física'),
('ING265', 'Laboratório de Engenharia'),
('QUI266', 'Laboratório de Realidade Virtual'),
('QUI266', 'Sala de Desenvolvimento de Software'),
('QUI266', 'Laboratório de Redes'),
('INF267', 'Laboratório de Robótica'),
('INF267', 'Oficina de Mecânica'),
('INF267', 'Sala de Desenvolvimento de Software'),
('ING268', 'Laboratório de Matemática'),
('ING268', 'Laboratório de Biologia'),
('ING268', 'Laboratório de História'),
('QUI269', 'Laboratório de Química'),
('QUI269', 'Laboratório de Biologia'),
('QUI269', 'Quadra Poliesportiva'),
('POR270', 'Laboratório de Produção de Vídeo'),
('POR270', 'Cantina'),
('POR270', 'Laboratório de Automação'),
('POR271', 'Sala de Atendimento Psicológico'),
('POR271', 'Sala de Impressão 3D'),
('POR271', 'Laboratório de Automação'),
('BIO272', 'Sala de Modelagem 3D'),
('BIO272', 'Sala de Estudo Individual'),
('BIO272', 'Laboratório de Análise de Dados'),
('MAT273', 'Sala de Jogos Educativos'),
('MAT273', 'Laboratório de Robótica'),
('MAT273', 'Sala de Empreendedorismo'),
('HIS274', 'Laboratório de Física'),
('HIS274', 'Sala de Jogos Educativos'),
('HIS274', 'Laboratório de Engenharia Química'),
('BIO275', 'Laboratório de Design Gráfico'),
('BIO275', 'Laboratório de Realidade Virtual'),
('BIO275', 'Biblioteca'),
('ART276', 'Sala de Música'),
('ART276', 'Sala de Leitura'),
('ART276', 'Laboratório de Fotografia'),
('INF277', 'Laboratório de Fotografia'),
('INF277', 'Laboratório de Inteligência Artificial'),
('INF277', 'Sala de Música'),
('ING278', 'Laboratório de Matemática'),
('ING278', 'Refeitório'),
('ING278', 'Laboratório de Eletrônica'),
('QUI279', 'Laboratório de Inteligência Artificial'),
('QUI279', 'Laboratório de Química'),
('QUI279', 'Sala de Atendimento Psicológico'),
('QUI280', 'Laboratório de Eletrônica'),
('QUI280', 'Laboratório de Nutrição'),
('QUI280', 'Laboratório de Microbiologia'),
('HIS281', 'Sala de Estudos Interdisciplinares'),
('HIS281', 'Laboratório de Física'),
('HIS281', 'Laboratório de Redes'),
('POR282', 'Sala de Leitura'),
('POR282', 'Laboratório de Matemática'),
('POR282', 'Cantina'),
('QUI283', 'Laboratório de Química'),
('QUI283', 'Laboratório de Automação'),
('QUI283', 'Refeitório'),
('HIS284', 'Laboratório de Geografia'),
('HIS284', 'Laboratório de Microbiologia'),
('HIS284', 'Sala de Informática'),
('QUI285', 'Laboratório de Robótica'),
('QUI285', 'Laboratório de Geografia'),
('QUI285', 'Laboratório de Línguas'),
('POR286', 'Sala de Artes'),
('POR286', 'Laboratório de Robótica'),
('POR286', 'Laboratório de Inteligência Artificial'),
('ART287', 'Laboratório de Engenharia'),
('ART287', 'Sala de Projeção'),
('ART287', 'Sala de Informática'),
('ING288', 'Sala de Coordenação'),
('ING288', 'Sala de Impressão 3D'),
('ING288', 'Laboratório de Geografia'),
('BIO289', 'Sala de Estudos Interdisciplinares'),
('BIO289', 'Refeitório'),
('BIO289', 'Laboratório de Eletrônica'),
('EDF290', 'Laboratório de Biologia'),
('EDF290', 'Laboratório de Realidade Virtual'),
('EDF290', 'Laboratório de Microbiologia'),
('GEO291', 'Laboratório de Línguas'),
('GEO291', 'Laboratório de Construção Civil'),
('GEO291', 'Sala dos Professores'),
('QUI292', 'Laboratório de Ciência dos Materiais'),
('QUI292', 'Oficina de Mecânica'),
('QUI292', 'Sala de Jogos Educativos'),
('HIS293', 'Laboratório de Microbiologia'),
('HIS293', 'Sala de Impressão 3D'),
('HIS293', 'Laboratório de Análise de Dados'),
('POR294', 'Laboratório de Biologia'),
('POR294', 'Laboratório de História'),
('POR294', 'Sala de Informática'),
('EDF295', 'Laboratório de Construção Civil'),
('EDF295', 'Laboratório de Engenharia Química'),
('EDF295', 'Sala dos Professores'),
('ING296', 'Laboratório de Química'),
('ING296', 'Laboratório de Meio Ambiente'),
('ING296', 'Sala de Informática'),
('EDF297', 'Laboratório de Geografia'),
('EDF297', 'Sala dos Professores'),
('EDF297', 'Laboratório de Meio Ambiente'),
('POR298', 'Sala de Modelagem 3D'),
('POR298', 'Sala de Atendimento Psicológico'),
('POR298', 'Laboratório de Engenharia Química'),
('MAT299', 'Laboratório de Engenharia Química'),
('MAT299', 'Sala de Desenvolvimento de Software'),
('MAT299', 'Laboratório de Engenharia'),
('HIS300', 'Laboratório de Realidade Virtual'),
('HIS300', 'Laboratório de Robótica'),
('HIS300', 'Laboratório de Análise de Dados'),
('QUI301', 'Laboratório de História'),
('QUI301', 'Sala de Impressão 3D'),
('QUI301', 'Laboratório de Microbiologia'),
('HIS302', 'Estúdio de Gravação'),
('HIS302', 'Laboratório de Automação'),
('HIS302', 'Sala de Jogos Educativos'),
('HIS303', 'Sala de Coordenação'),
('HIS303', 'Laboratório de Química'),
('HIS303', 'Laboratório de Realidade Virtual'),
('ING304', 'Laboratório de Física'),
('ING304', 'Sala de Atendimento Psicológico'),
('ING304', 'Laboratório de Engenharia Química'),
('ING305', 'Laboratório de Robótica'),
('ING305', 'Laboratório de Análises Clínicas'),
('ING305', 'Laboratório de Fotografia'),
('EDF306', 'Laboratório de Engenharia'),
('EDF306', 'Laboratório de Análise de Dados'),
('EDF306', 'Sala dos Professores'),
('MAT307', 'Refeitório'),
('MAT307', 'Laboratório de Realidade Virtual'),
('MAT307', 'Sala de Impressão 3D'),
('ART308', 'Sala de Atendimento Psicológico'),
('ART308', 'Laboratório de Programação'),
('ART308', 'Laboratório de Análises Clínicas'),
('ART309', 'Laboratório de Geografia'),
('ART309', 'Sala de Atendimento Psicológico'),
('ART309', 'Laboratório de Fotografia'),
('FIS310', 'Sala de Projeção'),
('FIS310', 'Sala de Atendimento Psicológico'),
('FIS310', 'Sala de Jogos Educativos'),
('GEO311', 'Laboratório de Microbiologia'),
('GEO311', 'Laboratório de Matemática'),
('GEO311', 'Laboratório de Realidade Virtual'),
('INF312', 'Laboratório de Robótica'),
('INF312', 'Sala dos Professores'),
('INF312', 'Sala de Estudo em Grupo'),
('FIS313', 'Laboratório de Realidade Virtual'),
('FIS313', 'Sala de Estudo em Grupo'),
('FIS313', 'Laboratório de Microbiologia'),
('EDF314', 'Sala de Jogos Educativos'),
('EDF314', 'Laboratório de História'),
('EDF314', 'Laboratório de Biologia'),
('POR315', 'Quadra Poliesportiva'),
('POR315', 'Sala de Desenvolvimento de Software'),
('POR315', 'Sala de Música'),
('BIO316', 'Sala de Empreendedorismo'),
('BIO316', 'Refeitório'),
('BIO316', 'Laboratório de Nutrição'),
('MAT317', 'Sala de Projeção'),
('MAT317', 'Laboratório de Química'),
('MAT317', 'Laboratório de Línguas'),
('EDF318', 'Sala de Jogos Educativos'),
('EDF318', 'Sala de Informática'),
('EDF318', 'Sala de Desenvolvimento de Software'),
('QUI319', 'Laboratório de Meio Ambiente'),
('QUI319', 'Laboratório de Fotografia'),
('QUI319', 'Laboratório de Programação'),
('QUI320', 'Laboratório de Meio Ambiente'),
('QUI320', 'Sala de Estudos Interdisciplinares'),
('QUI320', 'Sala de Modelagem 3D'),
('HIS321', 'Laboratório de Fotografia'),
('HIS321', 'Cantina'),
('HIS321', 'Sala de Estudo em Grupo'),
('GEO322', 'Laboratório de Análises Clínicas'),
('GEO322', 'Laboratório de Realidade Virtual'),
('GEO322', 'Laboratório de Nutrição'),
('ART323', 'Laboratório de Análises Clínicas'),
('ART323', 'Sala de Defesas de TCC'),
('ART323', 'Sala de Estudos Interdisciplinares'),
('HIS324', 'Laboratório de Nutrição'),
('HIS324', 'Refeitório'),
('HIS324', 'Laboratório de História'),
('ART325', 'Laboratório de Fotografia'),
('ART325', 'Sala de Estudo Individual'),
('ART325', 'Estúdio de Gravação'),
('QUI326', 'Biblioteca'),
('QUI326', 'Laboratório de Microbiologia'),
('QUI326', 'Laboratório de Línguas'),
('POR327', 'Sala de Projeção'),
('POR327', 'Laboratório de Design Gráfico'),
('POR327', 'Laboratório de Línguas'),
('BIO328', 'Laboratório de Realidade Virtual'),
('BIO328', 'Laboratório de Línguas'),
('BIO328', 'Laboratório de Produção de Vídeo'),
('INF329', 'Laboratório de Inteligência Artificial'),
('INF329', 'Laboratório de Química'),
('INF329', 'Sala de Informática'),
('MAT330', 'Laboratório de Realidade Virtual'),
('MAT330', 'Biblioteca'),
('MAT330', 'Sala de Atendimento Psicológico'),
('EDF331', 'Laboratório de Física'),
('EDF331', 'Laboratório de Programação'),
('EDF331', 'Laboratório de História'),
('GEO332', 'Sala de Informática'),
('GEO332', 'Laboratório de Física'),
('GEO332', 'Quadra Poliesportiva'),
('INF333', 'Laboratório de Engenharia'),
('INF333', 'Sala de Música'),
('INF333', 'Laboratório de Geografia'),
('ING334', 'Sala de Artes'),
('ING334', 'Sala de Defesas de TCC'),
('ING334', 'Sala de Modelagem 3D'),
('MAT335', 'Sala de Jogos Educativos'),
('MAT335', 'Oficina de Mecânica'),
('MAT335', 'Laboratório de Inteligência Artificial'),
('ING336', 'Laboratório de Análises Clínicas'),
('ING336', 'Sala de Estudo em Grupo'),
('ING336', 'Sala de Estudo Individual'),
('ART337', 'Biblioteca'),
('ART337', 'Sala de Modelagem 3D'),
('ART337', 'Laboratório de Microbiologia'),
('EDF338', 'Sala de Jogos Educativos'),
('EDF338', 'Laboratório de Robótica'),
('EDF338', 'Sala de Projeção'),
('EDF339', 'Sala de Empreendedorismo'),
('EDF339', 'Laboratório de Automação'),
('EDF339', 'Laboratório de Microbiologia'),
('BIO340', 'Sala de Música'),
('BIO340', 'Sala de Projeção'),
('BIO340', 'Laboratório de Química'),
('POR341', 'Laboratório de Robótica'),
('POR341', 'Sala de Empreendedorismo'),
('POR341', 'Laboratório de Física'),
('ART342', 'Laboratório de Línguas'),
('ART342', 'Laboratório de Automação'),
('ART342', 'Laboratório de Geografia'),
('MAT343', 'Laboratório de Robótica'),
('MAT343', 'Estúdio de Gravação'),
('MAT343', 'Laboratório de Línguas'),
('POR344', 'Auditório'),
('POR344', 'Laboratório de Matemática'),
('POR344', 'Sala de Impressão 3D'),
('GEO345', 'Laboratório de Microbiologia'),
('GEO345', 'Sala de Empreendedorismo'),
('GEO345', 'Sala de Informática'),
('QUI346', 'Sala de Artes'),
('QUI346', 'Biblioteca'),
('QUI346', 'Laboratório de Análises Clínicas'),
('QUI347', 'Laboratório de Design Gráfico'),
('QUI347', 'Sala de Impressão 3D'),
('QUI347', 'Quadra Poliesportiva'),
('BIO348', 'Auditório'),
('BIO348', 'Laboratório de Física'),
('BIO348', 'Laboratório de Ciência dos Materiais'),
('ART349', 'Laboratório de Biologia'),
('ART349', 'Quadra Poliesportiva'),
('ART349', 'Sala de Defesas de TCC'),
('ING350', 'Laboratório de Análise de Dados'),
('ING350', 'Sala de Atendimento Psicológico'),
('ING350', 'Oficina de Mecânica'),
('BIO351', 'Sala de Projeção'),
('BIO351', 'Laboratório de Biologia'),
('BIO351', 'Laboratório de Programação'),
('HIS352', 'Sala de Informática'),
('HIS352', 'Auditório'),
('HIS352', 'Sala dos Professores'),
('MAT353', 'Sala de Estudo Individual'),
('MAT353', 'Sala de Coordenação'),
('MAT353', 'Laboratório de Meio Ambiente'),
('POR354', 'Laboratório de Línguas'),
('POR354', 'Sala de Estudo em Grupo'),
('POR354', 'Laboratório de Eletrônica'),
('INF355', 'Sala de Projeção'),
('INF355', 'Laboratório de Construção Civil'),
('INF355', 'Sala de Desenvolvimento de Software'),
('MAT356', 'Sala de Música'),
('MAT356', 'Sala de Coordenação'),
('MAT356', 'Laboratório de Análises Clínicas'),
('ART357', 'Sala de Projeção'),
('ART357', 'Sala de Defesas de TCC'),
('ART357', 'Laboratório de Química'),
('GEO358', 'Quadra Poliesportiva'),
('GEO358', 'Sala de Estudo em Grupo'),
('GEO358', 'Laboratório de Microbiologia'),
('ING359', 'Laboratório de Física'),
('ING359', 'Laboratório de Engenharia'),
('ING359', 'Sala de Empreendedorismo'),
('HIS360', 'Laboratório de Inteligência Artificial'),
('HIS360', 'Laboratório de Meio Ambiente'),
('HIS360', 'Sala de Atendimento Psicológico'),
('QUI361', 'Sala de Informática'),
('QUI361', 'Laboratório de Biologia'),
('QUI361', 'Laboratório de Programação'),
('INF362', 'Laboratório de Eletrônica'),
('INF362', 'Laboratório de Química'),
('INF362', 'Sala de Jogos Educativos'),
('ART363', 'Sala de Jogos Educativos'),
('ART363', 'Laboratório de Programação'),
('ART363', 'Sala de Modelagem 3D'),
('ING364', 'Quadra Poliesportiva'),
('ING364', 'Sala de Coordenação'),
('ING364', 'Laboratório de Ciência dos Materiais'),
('EDF365', 'Laboratório de Matemática'),
('EDF365', 'Laboratório de Meio Ambiente'),
('EDF365', 'Cantina'),
('EDF366', 'Sala de Estudos Interdisciplinares'),
('EDF366', 'Laboratório de Meio Ambiente'),
('EDF366', 'Laboratório de Construção Civil'),
('GEO367', 'Laboratório de Meio Ambiente'),
('GEO367', 'Laboratório de Realidade Virtual'),
('GEO367', 'Sala de Estudo em Grupo'),
('INF368', 'Sala de Projeção'),
('INF368', 'Laboratório de Biologia'),
('INF368', 'Sala de Informática'),
('QUI369', 'Laboratório de Engenharia'),
('QUI369', 'Estúdio de Gravação'),
('QUI369', 'Sala dos Professores'),
('ING370', 'Laboratório de Microbiologia'),
('ING370', 'Sala de Atendimento Psicológico'),
('ING370', 'Sala de Música'),
('HIS371', 'Laboratório de Química'),
('HIS371', 'Sala de Informática'),
('HIS371', 'Laboratório de Ciência dos Materiais'),
('QUI372', 'Cantina'),
('QUI372', 'Laboratório de Eletrônica'),
('QUI372', 'Laboratório de Redes'),
('BIO373', 'Laboratório de Engenharia'),
('BIO373', 'Laboratório de Produção de Vídeo'),
('BIO373', 'Sala de Jogos Educativos'),
('HIS374', 'Sala de Música'),
('HIS374', 'Estúdio de Gravação'),
('HIS374', 'Sala de Atendimento Psicológico'),
('BIO375', 'Laboratório de Química'),
('BIO375', 'Sala de Defesas de TCC'),
('BIO375', 'Laboratório de História'),
('EDF376', 'Laboratório de Nutrição'),
('EDF376', 'Quadra Poliesportiva'),
('EDF376', 'Estúdio de Gravação'),
('INF377', 'Laboratório de Química'),
('INF377', 'Laboratório de Biologia'),
('INF377', 'Laboratório de Engenharia Química'),
('GEO378', 'Laboratório de Fotografia'),
('GEO378', 'Laboratório de Geografia'),
('GEO378', 'Sala de Música'),
('GEO379', 'Laboratório de Robótica'),
('GEO379', 'Laboratório de Realidade Virtual'),
('GEO379', 'Laboratório de Química'),
('POR380', 'Sala de Estudos Interdisciplinares'),
('POR380', 'Sala de Projeção'),
('POR380', 'Laboratório de Biologia'),
('FIS381', 'Laboratório de Análise de Dados'),
('FIS381', 'Laboratório de Realidade Virtual'),
('FIS381', 'Sala de Estudo Individual'),
('ING382', 'Laboratório de Meio Ambiente'),
('ING382', 'Laboratório de Eletrônica'),
('ING382', 'Sala de Desenvolvimento de Software'),
('BIO383', 'Sala de Impressão 3D'),
('BIO383', 'Sala de Empreendedorismo'),
('BIO383', 'Laboratório de História'),
('POR384', 'Sala de Jogos Educativos'),
('POR384', 'Laboratório de Redes'),
('POR384', 'Laboratório de Química'),
('ING385', 'Sala de Impressão 3D'),
('ING385', 'Laboratório de Microbiologia'),
('ING385', 'Refeitório'),
('BIO386', 'Cantina'),
('BIO386', 'Laboratório de Engenharia Química'),
('BIO386', 'Sala de Desenvolvimento de Software'),
('GEO387', 'Sala de Estudos Interdisciplinares'),
('GEO387', 'Laboratório de Engenharia'),
('GEO387', 'Sala dos Professores'),
('POR388', 'Laboratório de Automação'),
('POR388', 'Laboratório de Matemática'),
('POR388', 'Sala de Desenvolvimento de Software'),
('ART389', 'Sala de Desenvolvimento de Software'),
('ART389', 'Cantina'),
('ART389', 'Laboratório de Línguas'),
('ART390', 'Laboratório de Biologia'),
('ART390', 'Sala de Estudo em Grupo'),
('ART390', 'Sala de Defesas de TCC'),
('BIO391', 'Laboratório de Análises Clínicas'),
('BIO391', 'Sala de Informática'),
('BIO391', 'Sala de Atendimento Psicológico'),
('QUI392', 'Laboratório de Produção de Vídeo'),
('QUI392', 'Sala de Artes'),
('QUI392', 'Laboratório de Biologia'),
('ING393', 'Laboratório de Microbiologia'),
('ING393', 'Laboratório de Línguas'),
('ING393', 'Laboratório de Construção Civil'),
('FIS394', 'Biblioteca'),
('FIS394', 'Oficina de Mecânica'),
('FIS394', 'Cantina'),
('EDF395', 'Laboratório de Engenharia'),
('EDF395', 'Laboratório de Microbiologia'),
('EDF395', 'Laboratório de Meio Ambiente'),
('ART396', 'Sala de Estudos Interdisciplinares'),
('ART396', 'Biblioteca'),
('ART396', 'Estúdio de Gravação'),
('ART397', 'Sala de Desenvolvimento de Software'),
('ART397', 'Laboratório de Matemática'),
('ART397', 'Sala de Música'),
('INF398', 'Sala de Jogos Educativos'),
('INF398', 'Sala de Leitura'),
('INF398', 'Sala de Estudos Interdisciplinares'),
('ART399', 'Estúdio de Gravação'),
('ART399', 'Sala de Defesas de TCC'),
('ART399', 'Sala de Estudos Interdisciplinares'),
('POR400', 'Sala dos Professores'),
('POR400', 'Cantina'),
('POR400', 'Biblioteca'),
('EDF401', 'Sala de Projeção'),
('EDF401', 'Quadra Poliesportiva'),
('EDF401', 'Laboratório de História'),
('GEO402', 'Laboratório de Microbiologia'),
('GEO402', 'Laboratório de Geografia'),
('GEO402', 'Quadra Poliesportiva'),
('FIS403', 'Sala de Estudos Interdisciplinares'),
('FIS403', 'Sala de Impressão 3D'),
('FIS403', 'Sala de Projeção'),
('EDF404', 'Sala dos Professores'),
('EDF404', 'Estúdio de Gravação'),
('EDF404', 'Sala de Modelagem 3D'),
('POR405', 'Sala de Estudo Individual'),
('POR405', 'Laboratório de Engenharia'),
('POR405', 'Laboratório de Nutrição'),
('POR406', 'Quadra Poliesportiva'),
('POR406', 'Laboratório de Física'),
('POR406', 'Laboratório de Robótica'),
('MAT407', 'Laboratório de Fotografia'),
('MAT407', 'Sala de Jogos Educativos'),
('MAT407', 'Laboratório de Inteligência Artificial'),
('ART408', 'Laboratório de História'),
('ART408', 'Laboratório de Design Gráfico'),
('ART408', 'Laboratório de Realidade Virtual'),
('QUI409', 'Sala de Impressão 3D'),
('QUI409', 'Laboratório de Geografia'),
('QUI409', 'Laboratório de Design Gráfico'),
('ING410', 'Sala de Modelagem 3D'),
('ING410', 'Sala de Estudo em Grupo'),
('ING410', 'Refeitório'),
('ART411', 'Laboratório de Línguas'),
('ART411', 'Sala de Impressão 3D'),
('ART411', 'Laboratório de Análise de Dados'),
('ART412', 'Sala de Estudo em Grupo'),
('ART412', 'Laboratório de Nutrição'),
('ART412', 'Refeitório'),
('HIS413', 'Laboratório de Automação'),
('HIS413', 'Laboratório de Fotografia'),
('HIS413', 'Sala de Impressão 3D'),
('MAT414', 'Laboratório de Inteligência Artificial'),
('MAT414', 'Cantina'),
('MAT414', 'Sala de Artes'),
('ING415', 'Laboratório de Microbiologia'),
('ING415', 'Sala dos Professores'),
('ING415', 'Sala de Música'),
('EDF416', 'Laboratório de Produção de Vídeo'),
('EDF416', 'Laboratório de Matemática'),
('EDF416', 'Laboratório de Automação'),
('FIS417', 'Estúdio de Gravação'),
('FIS417', 'Sala dos Professores'),
('FIS417', 'Laboratório de Biologia'),
('HIS418', 'Laboratório de Geografia'),
('HIS418', 'Refeitório'),
('HIS418', 'Laboratório de Microbiologia'),
('BIO419', 'Sala de Artes'),
('BIO419', 'Cantina'),
('BIO419', 'Sala de Atendimento Psicológico'),
('POR420', 'Sala de Estudos Interdisciplinares'),
('POR420', 'Refeitório'),
('POR420', 'Sala de Estudo Individual'),
('QUI421', 'Laboratório de Programação'),
('QUI421', 'Laboratório de Nutrição'),
('QUI421', 'Sala de Informática'),
('FIS422', 'Biblioteca'),
('FIS422', 'Sala de Desenvolvimento de Software'),
('FIS422', 'Laboratório de Química'),
('QUI423', 'Laboratório de Construção Civil'),
('QUI423', 'Laboratório de Nutrição'),
('QUI423', 'Laboratório de Química'),
('ART424', 'Sala dos Professores'),
('ART424', 'Laboratório de Química'),
('ART424', 'Sala de Jogos Educativos'),
('ING425', 'Oficina de Mecânica'),
('ING425', 'Sala de Atendimento Psicológico'),
('ING425', 'Sala de Desenvolvimento de Software'),
('FIS426', 'Laboratório de Meio Ambiente'),
('FIS426', 'Laboratório de Inteligência Artificial'),
('FIS426', 'Laboratório de Realidade Virtual'),
('EDF427', 'Sala de Estudos Interdisciplinares'),
('EDF427', 'Sala de Projeção'),
('EDF427', 'Sala de Empreendedorismo'),
('BIO428', 'Sala de Estudos Interdisciplinares'),
('BIO428', 'Sala de Estudo Individual'),
('BIO428', 'Laboratório de Matemática'),
('HIS429', 'Sala de Estudo em Grupo'),
('HIS429', 'Laboratório de Redes'),
('HIS429', 'Laboratório de Línguas'),
('HIS430', 'Laboratório de Nutrição'),
('HIS430', 'Sala de Empreendedorismo'),
('HIS430', 'Laboratório de Análises Clínicas'),
('BIO431', 'Laboratório de Fotografia'),
('BIO431', 'Sala de Modelagem 3D'),
('BIO431', 'Laboratório de Realidade Virtual'),
('ART432', 'Laboratório de Análises Clínicas'),
('ART432', 'Laboratório de Automação'),
('ART432', 'Laboratório de Programação'),
('GEO433', 'Sala de Defesas de TCC'),
('GEO433', 'Laboratório de Engenharia Química'),
('GEO433', 'Sala de Estudos Interdisciplinares'),
('POR434', 'Laboratório de Nutrição'),
('POR434', 'Sala de Coordenação'),
('POR434', 'Sala de Estudo em Grupo'),
('MAT435', 'Laboratório de Nutrição'),
('MAT435', 'Sala de Atendimento Psicológico'),
('MAT435', 'Laboratório de Eletrônica'),
('GEO436', 'Laboratório de Nutrição'),
('GEO436', 'Laboratório de Automação'),
('GEO436', 'Laboratório de Microbiologia'),
('MAT437', 'Sala de Desenvolvimento de Software'),
('MAT437', 'Laboratório de Biologia'),
('MAT437', 'Laboratório de Inteligência Artificial'),
('GEO438', 'Laboratório de Fotografia'),
('GEO438', 'Laboratório de Engenharia'),
('GEO438', 'Sala de Atendimento Psicológico'),
('POR439', 'Sala de Estudos Interdisciplinares'),
('POR439', 'Laboratório de Meio Ambiente'),
('POR439', 'Sala de Atendimento Psicológico'),
('MAT440', 'Laboratório de Construção Civil'),
('MAT440', 'Laboratório de Eletrônica'),
('MAT440', 'Sala de Música'),
('ING441', 'Sala de Jogos Educativos'),
('ING441', 'Laboratório de Inteligência Artificial'),
('ING441', 'Laboratório de Redes'),
('POR442', 'Sala de Modelagem 3D'),
('POR442', 'Sala de Defesas de TCC'),
('POR442', 'Laboratório de Microbiologia'),
('ING443', 'Laboratório de Análise de Dados'),
('ING443', 'Laboratório de Programação'),
('ING443', 'Sala de Informática'),
('POR444', 'Sala de Música'),
('POR444', 'Refeitório'),
('POR444', 'Laboratório de História'),
('FIS445', 'Sala de Informática'),
('FIS445', 'Laboratório de Física'),
('FIS445', 'Sala de Jogos Educativos'),
('POR446', 'Laboratório de Construção Civil'),
('POR446', 'Oficina de Mecânica'),
('POR446', 'Estúdio de Gravação'),
('BIO447', 'Sala de Coordenação'),
('BIO447', 'Sala de Defesas de TCC'),
('BIO447', 'Sala de Projeção'),
('ART448', 'Sala de Empreendedorismo'),
('ART448', 'Laboratório de Análise de Dados'),
('ART448', 'Cantina'),
('ART449', 'Laboratório de Engenharia Química'),
('ART449', 'Laboratório de Automação'),
('ART449', 'Laboratório de Eletrônica'),
('QUI450', 'Cantina'),
('QUI450', 'Laboratório de Ciência dos Materiais'),
('QUI450', 'Sala de Desenvolvimento de Software'),
('EDF451', 'Cantina'),
('EDF451', 'Sala de Coordenação'),
('EDF451', 'Laboratório de Física'),
('FIS452', 'Laboratório de Nutrição'),
('FIS452', 'Laboratório de Fotografia'),
('FIS452', 'Sala de Leitura'),
('ART453', 'Sala de Empreendedorismo'),
('ART453', 'Sala de Projeção'),
('ART453', 'Laboratório de Realidade Virtual'),
('FIS454', 'Refeitório'),
('FIS454', 'Sala de Informática'),
('FIS454', 'Laboratório de Fotografia'),
('ING455', 'Sala de Estudo Individual'),
('ING455', 'Estúdio de Gravação'),
('ING455', 'Laboratório de Biologia'),
('ART456', 'Cantina'),
('ART456', 'Laboratório de Análise de Dados'),
('ART456', 'Sala de Estudos Interdisciplinares'),
('MAT457', 'Sala de Jogos Educativos'),
('MAT457', 'Laboratório de Construção Civil'),
('MAT457', 'Oficina de Mecânica'),
('EDF458', 'Biblioteca'),
('EDF458', 'Laboratório de Análise de Dados'),
('EDF458', 'Laboratório de Fotografia'),
('BIO459', 'Laboratório de Matemática'),
('BIO459', 'Laboratório de Análise de Dados'),
('BIO459', 'Sala de Informática'),
('MAT460', 'Laboratório de Engenharia'),
('MAT460', 'Sala de Coordenação'),
('MAT460', 'Sala de Leitura'),
('MAT461', 'Laboratório de Física'),
('MAT461', 'Laboratório de Análise de Dados'),
('MAT461', 'Sala de Empreendedorismo'),
('HIS462', 'Laboratório de Matemática'),
('HIS462', 'Laboratório de Química'),
('HIS462', 'Laboratório de Produção de Vídeo'),
('ING463', 'Laboratório de Engenharia Química'),
('ING463', 'Sala de Modelagem 3D'),
('ING463', 'Cantina'),
('GEO464', 'Laboratório de Produção de Vídeo'),
('GEO464', 'Laboratório de Análise de Dados'),
('GEO464', 'Sala dos Professores'),
('EDF465', 'Laboratório de Programação'),
('EDF465', 'Laboratório de Química'),
('EDF465', 'Sala dos Professores'),
('ING466', 'Laboratório de Engenharia Química'),
('ING466', 'Laboratório de Geografia'),
('ING466', 'Sala de Projeção'),
('MAT467', 'Laboratório de Inteligência Artificial'),
('MAT467', 'Sala de Estudos Interdisciplinares'),
('MAT467', 'Sala de Artes'),
('BIO468', 'Sala de Estudo Individual'),
('BIO468', 'Sala de Empreendedorismo'),
('BIO468', 'Laboratório de Biologia'),
('INF469', 'Laboratório de Ciência dos Materiais'),
('INF469', 'Sala de Leitura'),
('INF469', 'Laboratório de Microbiologia'),
('MAT470', 'Sala de Jogos Educativos'),
('MAT470', 'Sala de Informática'),
('MAT470', 'Laboratório de Produção de Vídeo'),
('GEO471', 'Sala de Estudo Individual'),
('GEO471', 'Sala de Artes'),
('GEO471', 'Laboratório de Inteligência Artificial'),
('INF472', 'Sala de Coordenação'),
('INF472', 'Laboratório de Fotografia'),
('INF472', 'Laboratório de Eletrônica'),
('EDF473', 'Laboratório de Biologia'),
('EDF473', 'Laboratório de Automação'),
('EDF473', 'Laboratório de Matemática'),
('HIS474', 'Sala de Modelagem 3D'),
('HIS474', 'Laboratório de Microbiologia'),
('HIS474', 'Sala de Música'),
('BIO475', 'Biblioteca'),
('BIO475', 'Sala de Atendimento Psicológico'),
('BIO475', 'Sala de Informática'),
('BIO476', 'Sala de Defesas de TCC'),
('BIO476', 'Sala de Artes'),
('BIO476', 'Sala de Projeção'),
('BIO477', 'Laboratório de História'),
('BIO477', 'Sala de Projeção'),
('BIO477', 'Laboratório de Física'),
('ART478', 'Biblioteca'),
('ART478', 'Sala de Projeção'),
('ART478', 'Laboratório de Engenharia Química'),
('POR479', 'Laboratório de Produção de Vídeo'),
('POR479', 'Laboratório de Química'),
('POR479', 'Sala de Desenvolvimento de Software'),
('ART480', 'Laboratório de Biologia'),
('ART480', 'Laboratório de Línguas'),
('ART480', 'Sala de Projeção'),
('BIO481', 'Laboratório de Produção de Vídeo'),
('BIO481', 'Sala de Modelagem 3D'),
('BIO481', 'Sala de Estudo em Grupo'),
('QUI482', 'Sala de Informática'),
('QUI482', 'Sala de Coordenação'),
('QUI482', 'Laboratório de Física'),
('FIS483', 'Sala de Impressão 3D'),
('FIS483', 'Laboratório de Robótica'),
('FIS483', 'Sala dos Professores'),
('POR484', 'Laboratório de Programação'),
('POR484', 'Sala de Projeção'),
('POR484', 'Sala de Música'),
('BIO485', 'Laboratório de Línguas'),
('BIO485', 'Sala dos Professores'),
('BIO485', 'Laboratório de Microbiologia'),
('POR486', 'Laboratório de Eletrônica'),
('POR486', 'Laboratório de Robótica'),
('POR486', 'Laboratório de Química'),
('ING487', 'Biblioteca'),
('ING487', 'Sala de Música'),
('ING487', 'Sala de Estudo Individual'),
('QUI488', 'Laboratório de Fotografia'),
('QUI488', 'Laboratório de Meio Ambiente'),
('QUI488', 'Laboratório de Design Gráfico'),
('MAT489', 'Biblioteca'),
('MAT489', 'Laboratório de Produção de Vídeo'),
('MAT489', 'Laboratório de Nutrição'),
('ING490', 'Laboratório de Física'),
('ING490', 'Auditório'),
('ING490', 'Sala de Estudo em Grupo'),
('ART491', 'Laboratório de Automação'),
('ART491', 'Laboratório de Microbiologia'),
('ART491', 'Sala de Coordenação'),
('EDF492', 'Laboratório de Matemática'),
('EDF492', 'Sala de Coordenação'),
('EDF492', 'Cantina'),
('ING493', 'Sala de Projeção'),
('ING493', 'Sala de Empreendedorismo'),
('ING493', 'Laboratório de Produção de Vídeo'),
('MAT494', 'Refeitório'),
('MAT494', 'Laboratório de Análise de Dados'),
('MAT494', 'Oficina de Mecânica'),
('BIO495', 'Refeitório'),
('BIO495', 'Laboratório de Química'),
('BIO495', 'Laboratório de Design Gráfico'),
('ING496', 'Sala de Coordenação'),
('ING496', 'Oficina de Mecânica'),
('ING496', 'Sala de Projeção'),
('EDF497', 'Estúdio de Gravação'),
('EDF497', 'Sala de Empreendedorismo'),
('EDF497', 'Laboratório de História'),
('QUI498', 'Laboratório de Automação'),
('QUI498', 'Biblioteca'),
('QUI498', 'Oficina de Mecânica'),
('HIS499', 'Laboratório de Redes'),
('HIS499', 'Laboratório de Eletrônica'),
('HIS499', 'Sala de Artes'),
('GEO500', 'Laboratório de Engenharia Química'),
('GEO500', 'Laboratório de Microbiologia'),
('GEO500', 'Quadra Poliesportiva'),
('ART501', 'Laboratório de Redes'),
('ART501', 'Sala de Música'),
('ART501', 'Sala de Estudos Interdisciplinares'),
('ING502', 'Laboratório de Fotografia'),
('ING502', 'Laboratório de Engenharia'),
('ING502', 'Laboratório de Design Gráfico'),
('BIO503', 'Laboratório de Robótica'),
('BIO503', 'Sala de Modelagem 3D'),
('BIO503', 'Laboratório de Línguas'),
('ING504', 'Laboratório de Automação'),
('ING504', 'Laboratório de Redes'),
('ING504', 'Laboratório de Física'),
('MAT505', 'Sala de Modelagem 3D'),
('MAT505', 'Oficina de Mecânica'),
('MAT505', 'Laboratório de História'),
('QUI506', 'Cantina'),
('QUI506', 'Laboratório de História'),
('QUI506', 'Sala dos Professores'),
('GEO507', 'Sala de Atendimento Psicológico'),
('GEO507', 'Sala de Estudo em Grupo'),
('GEO507', 'Sala de Modelagem 3D'),
('ING508', 'Sala de Jogos Educativos'),
('ING508', 'Laboratório de Análises Clínicas'),
('ING508', 'Estúdio de Gravação'),
('GEO509', 'Laboratório de Inteligência Artificial'),
('GEO509', 'Oficina de Mecânica'),
('GEO509', 'Laboratório de Meio Ambiente'),
('GEO510', 'Sala de Leitura'),
('GEO510', 'Laboratório de Microbiologia'),
('GEO510', 'Laboratório de Geografia'),
('QUI511', 'Laboratório de Química'),
('QUI511', 'Auditório'),
('QUI511', 'Laboratório de Inteligência Artificial'),
('INF512', 'Laboratório de Nutrição'),
('INF512', 'Sala de Artes'),
('INF512', 'Laboratório de Física'),
('EDF513', 'Laboratório de Produção de Vídeo'),
('EDF513', 'Sala de Música'),
('EDF513', 'Sala de Modelagem 3D'),
('ING514', 'Sala de Impressão 3D'),
('ING514', 'Oficina de Mecânica'),
('ING514', 'Sala de Empreendedorismo'),
('ING515', 'Refeitório'),
('ING515', 'Laboratório de Produção de Vídeo'),
('ING515', 'Oficina de Mecânica'),
('QUI516', 'Sala de Leitura'),
('QUI516', 'Laboratório de Programação'),
('QUI516', 'Quadra Poliesportiva'),
('BIO517', 'Sala de Informática'),
('BIO517', 'Sala de Leitura'),
('BIO517', 'Laboratório de Ciência dos Materiais'),
('ART518', 'Laboratório de Análises Clínicas'),
('ART518', 'Laboratório de Línguas'),
('ART518', 'Sala de Coordenação'),
('EDF519', 'Sala de Projeção'),
('EDF519', 'Sala de Estudo em Grupo'),
('EDF519', 'Laboratório de Física'),
('BIO520', 'Refeitório'),
('BIO520', 'Sala de Estudos Interdisciplinares'),
('BIO520', 'Sala de Desenvolvimento de Software'),
('INF521', 'Laboratório de Química'),
('INF521', 'Laboratório de Nutrição'),
('INF521', 'Sala de Atendimento Psicológico'),
('HIS522', 'Estúdio de Gravação'),
('HIS522', 'Laboratório de Análise de Dados'),
('HIS522', 'Sala de Defesas de TCC'),
('GEO523', 'Sala de Impressão 3D'),
('GEO523', 'Laboratório de Nutrição'),
('GEO523', 'Sala de Atendimento Psicológico'),
('EDF524', 'Sala de Empreendedorismo'),
('EDF524', 'Laboratório de História'),
('EDF524', 'Sala de Atendimento Psicológico'),
('EDF525', 'Laboratório de História'),
('EDF525', 'Sala de Jogos Educativos'),
('EDF525', 'Laboratório de Fotografia'),
('BIO526', 'Sala de Estudo em Grupo'),
('BIO526', 'Laboratório de Química'),
('BIO526', 'Biblioteca'),
('FIS527', 'Sala de Impressão 3D'),
('FIS527', 'Laboratório de Biologia'),
('FIS527', 'Cantina'),
('GEO528', 'Laboratório de Meio Ambiente'),
('GEO528', 'Laboratório de Análise de Dados'),
('GEO528', 'Laboratório de Química'),
('GEO529', 'Laboratório de Design Gráfico'),
('GEO529', 'Sala de Leitura'),
('GEO529', 'Oficina de Mecânica'),
('GEO530', 'Sala de Modelagem 3D'),
('GEO530', 'Oficina de Mecânica'),
('GEO530', 'Laboratório de Química'),
('ART531', 'Laboratório de Construção Civil'),
('ART531', 'Refeitório'),
('ART531', 'Auditório'),
('EDF532', 'Laboratório de Programação'),
('EDF532', 'Sala de Artes'),
('EDF532', 'Biblioteca'),
('BIO533', 'Laboratório de Engenharia Química'),
('BIO533', 'Sala dos Professores'),
('BIO533', 'Laboratório de Geografia'),
('MAT534', 'Sala dos Professores'),
('MAT534', 'Laboratório de Produção de Vídeo'),
('MAT534', 'Sala de Atendimento Psicológico'),
('EDF535', 'Sala de Projeção'),
('EDF535', 'Sala de Música'),
('EDF535', 'Laboratório de Inteligência Artificial'),
('HIS536', 'Laboratório de Física'),
('HIS536', 'Laboratório de Engenharia'),
('HIS536', 'Laboratório de Geografia'),
('BIO537', 'Laboratório de História'),
('BIO537', 'Laboratório de Engenharia Química'),
('BIO537', 'Sala de Estudo Individual'),
('BIO538', 'Cantina'),
('BIO538', 'Refeitório'),
('BIO538', 'Laboratório de Nutrição'),
('MAT539', 'Laboratório de Física'),
('MAT539', 'Laboratório de Nutrição'),
('MAT539', 'Sala de Modelagem 3D'),
('GEO540', 'Estúdio de Gravação'),
('GEO540', 'Oficina de Mecânica'),
('GEO540', 'Sala de Coordenação'),
('EDF541', 'Laboratório de Produção de Vídeo'),
('EDF541', 'Biblioteca'),
('EDF541', 'Laboratório de Robótica'),
('ART542', 'Laboratório de Automação'),
('ART542', 'Sala de Impressão 3D'),
('ART542', 'Sala dos Professores'),
('QUI543', 'Laboratório de Biologia'),
('QUI543', 'Sala de Empreendedorismo'),
('QUI543', 'Cantina'),
('MAT544', 'Sala de Modelagem 3D'),
('MAT544', 'Laboratório de Engenharia'),
('MAT544', 'Sala de Estudos Interdisciplinares'),
('MAT545', 'Laboratório de Análises Clínicas'),
('MAT545', 'Laboratório de Eletrônica'),
('MAT545', 'Laboratório de Construção Civil'),
('POR546', 'Sala de Impressão 3D'),
('POR546', 'Sala de Estudo Individual'),
('POR546', 'Laboratório de Realidade Virtual'),
('EDF547', 'Quadra Poliesportiva'),
('EDF547', 'Laboratório de Análises Clínicas'),
('EDF547', 'Laboratório de Química'),
('POR548', 'Sala de Desenvolvimento de Software'),
('POR548', 'Laboratório de Eletrônica'),
('POR548', 'Laboratório de Ciência dos Materiais'),
('POR549', 'Sala de Defesas de TCC'),
('POR549', 'Sala de Estudo Individual'),
('POR549', 'Sala de Modelagem 3D'),
('GEO550', 'Laboratório de Análises Clínicas'),
('GEO550', 'Laboratório de Ciência dos Materiais'),
('GEO550', 'Laboratório de Robótica'),
('BIO551', 'Biblioteca'),
('BIO551', 'Laboratório de Realidade Virtual'),
('BIO551', 'Laboratório de Engenharia Química'),
('INF552', 'Sala de Artes'),
('INF552', 'Laboratório de Produção de Vídeo'),
('INF552', 'Biblioteca'),
('EDF553', 'Sala de Empreendedorismo'),
('EDF553', 'Sala de Coordenação'),
('EDF553', 'Laboratório de Ciência dos Materiais'),
('FIS554', 'Sala de Artes'),
('FIS554', 'Laboratório de Eletrônica'),
('FIS554', 'Laboratório de Produção de Vídeo'),
('GEO555', 'Laboratório de Redes'),
('GEO555', 'Refeitório'),
('GEO555', 'Sala de Estudo Individual'),
('QUI556', 'Sala de Atendimento Psicológico'),
('QUI556', 'Laboratório de Realidade Virtual'),
('QUI556', 'Refeitório'),
('INF557', 'Laboratório de Química'),
('INF557', 'Laboratório de Matemática'),
('INF557', 'Laboratório de Análises Clínicas'),
('FIS558', 'Sala de Desenvolvimento de Software'),
('FIS558', 'Sala de Defesas de TCC'),
('FIS558', 'Sala de Projeção'),
('QUI559', 'Sala de Estudo em Grupo'),
('QUI559', 'Laboratório de Eletrônica'),
('QUI559', 'Laboratório de Microbiologia'),
('EDF560', 'Laboratório de Engenharia Química'),
('EDF560', 'Sala de Estudos Interdisciplinares'),
('EDF560', 'Laboratório de Microbiologia'),
('INF561', 'Oficina de Mecânica'),
('INF561', 'Laboratório de Construção Civil'),
('INF561', 'Sala de Defesas de TCC'),
('INF562', 'Sala de Música'),
('INF562', 'Laboratório de Biologia'),
('INF562', 'Laboratório de Línguas'),
('QUI563', 'Laboratório de Biologia'),
('QUI563', 'Auditório'),
('QUI563', 'Laboratório de Nutrição'),
('HIS564', 'Oficina de Mecânica'),
('HIS564', 'Sala dos Professores'),
('HIS564', 'Laboratório de Engenharia'),
('QUI565', 'Laboratório de Design Gráfico'),
('QUI565', 'Estúdio de Gravação'),
('QUI565', 'Laboratório de Análises Clínicas'),
('BIO566', 'Laboratório de Engenharia Química'),
('BIO566', 'Laboratório de Construção Civil'),
('BIO566', 'Laboratório de Geografia'),
('ING567', 'Sala de Projeção'),
('ING567', 'Sala de Estudos Interdisciplinares'),
('ING567', 'Sala de Jogos Educativos'),
('MAT568', 'Laboratório de Análise de Dados'),
('MAT568', 'Laboratório de Design Gráfico'),
('MAT568', 'Laboratório de Biologia'),
('ING569', 'Sala de Artes'),
('ING569', 'Quadra Poliesportiva'),
('ING569', 'Laboratório de Automação'),
('POR570', 'Laboratório de Fotografia'),
('POR570', 'Laboratório de Engenharia'),
('POR570', 'Sala de Modelagem 3D'),
('ING571', 'Auditório'),
('ING571', 'Laboratório de Meio Ambiente'),
('ING571', 'Laboratório de Redes'),
('FIS572', 'Laboratório de Produção de Vídeo'),
('FIS572', 'Laboratório de Design Gráfico'),
('FIS572', 'Laboratório de Química'),
('FIS573', 'Sala de Estudos Interdisciplinares'),
('FIS573', 'Laboratório de Redes'),
('FIS573', 'Laboratório de Inteligência Artificial'),
('QUI574', 'Sala de Modelagem 3D'),
('QUI574', 'Laboratório de Microbiologia'),
('QUI574', 'Sala de Informática'),
('FIS575', 'Laboratório de História'),
('FIS575', 'Laboratório de Programação'),
('FIS575', 'Biblioteca'),
('FIS576', 'Cantina'),
('FIS576', 'Laboratório de Meio Ambiente'),
('FIS576', 'Laboratório de Nutrição'),
('HIS577', 'Laboratório de Nutrição'),
('HIS577', 'Refeitório'),
('HIS577', 'Auditório'),
('POR578', 'Laboratório de Física'),
('POR578', 'Laboratório de Inteligência Artificial'),
('POR578', 'Laboratório de Programação'),
('BIO579', 'Sala de Jogos Educativos'),
('BIO579', 'Sala de Artes'),
('BIO579', 'Laboratório de Construção Civil'),
('HIS580', 'Quadra Poliesportiva'),
('HIS580', 'Laboratório de Robótica'),
('HIS580', 'Laboratório de Microbiologia'),
('FIS581', 'Laboratório de Inteligência Artificial'),
('FIS581', 'Estúdio de Gravação'),
('FIS581', 'Sala de Desenvolvimento de Software'),
('MAT582', 'Quadra Poliesportiva'),
('MAT582', 'Laboratório de Análise de Dados'),
('MAT582', 'Laboratório de Inteligência Artificial'),
('ING583', 'Oficina de Mecânica'),
('ING583', 'Sala de Estudo Individual'),
('ING583', 'Sala de Estudos Interdisciplinares'),
('BIO584', 'Sala de Atendimento Psicológico'),
('BIO584', 'Sala de Impressão 3D'),
('BIO584', 'Sala de Estudo em Grupo'),
('GEO585', 'Sala de Desenvolvimento de Software'),
('GEO585', 'Sala de Empreendedorismo'),
('GEO585', 'Sala de Projeção'),
('BIO586', 'Laboratório de Fotografia'),
('BIO586', 'Laboratório de História'),
('BIO586', 'Laboratório de Análises Clínicas'),
('GEO587', 'Laboratório de Construção Civil'),
('GEO587', 'Sala de Projeção'),
('GEO587', 'Refeitório'),
('MAT588', 'Sala de Coordenação'),
('MAT588', 'Estúdio de Gravação'),
('MAT588', 'Sala de Leitura'),
('POR589', 'Sala de Coordenação'),
('POR589', 'Sala de Jogos Educativos'),
('POR589', 'Laboratório de Ciência dos Materiais'),
('MAT590', 'Sala de Estudos Interdisciplinares'),
('MAT590', 'Sala de Desenvolvimento de Software'),
('MAT590', 'Laboratório de Fotografia'),
('GEO591', 'Quadra Poliesportiva'),
('GEO591', 'Sala de Desenvolvimento de Software'),
('GEO591', 'Laboratório de Análise de Dados'),
('FIS592', 'Sala de Defesas de TCC'),
('FIS592', 'Sala de Empreendedorismo'),
('FIS592', 'Laboratório de Matemática'),
('HIS593', 'Sala de Jogos Educativos'),
('HIS593', 'Laboratório de Nutrição'),
('HIS593', 'Laboratório de Línguas'),
('MAT594', 'Laboratório de Produção de Vídeo'),
('MAT594', 'Laboratório de Ciência dos Materiais'),
('MAT594', 'Laboratório de Matemática'),
('BIO595', 'Oficina de Mecânica'),
('BIO595', 'Laboratório de Construção Civil'),
('BIO595', 'Laboratório de Ciência dos Materiais'),
('POR596', 'Sala de Música'),
('POR596', 'Laboratório de Análise de Dados'),
('POR596', 'Laboratório de Física'),
('ART597', 'Sala de Projeção'),
('ART597', 'Sala de Impressão 3D'),
('ART597', 'Laboratório de Nutrição'),
('ING598', 'Laboratório de História'),
('ING598', 'Sala de Artes'),
('ING598', 'Sala de Desenvolvimento de Software'),
('HIS599', 'Oficina de Mecânica'),
('HIS599', 'Laboratório de Inteligência Artificial'),
('HIS599', 'Laboratório de Construção Civil');