INSERT INTO REGRADISCIPLINA (Codigo_Disc, Tipo_Regra) VALUES
('BIO566', 'Regra de Reprovação XIV'),
('MAT457', 'Regra de Trabalho de Conclusão X'),
('MAT224', 'Regra de Transferência I'),
('GEO471', 'Regra de Aprovação XV'),
('EDF492', 'Regra de Frequência XIV'),
('MAT259', 'Regra de Cancelamento XV'),
('BIO477', 'Regra de Nota Mínima XI'),
('ART309', 'Regra de Disciplina XIII'),
('ING350', 'Regra de Matrícula II'),
('ING508', 'Regra de Matrícula II'),
('QUI103', 'Regra de Comportamento VIII'),
('POR298', 'Regra de Trabalho de Conclusão XI'),
('FIS403', 'Regra de Prova Final XII'),
('HIS499', 'Regra de Trabalho de Conclusão XII'),
('POR215', 'Regra de Aprovação VIII'),
('ART115', 'Regra de Transferência X'),
('GEO114', 'Regra de Frequência Mínima XV'),
('EDF216', 'Regra de Trabalho de Conclusão II'),
('INF119', 'Regra de Disciplina XII'),
('HIS593', 'Regra de Atividades Complementares XV'),
('HIS205', 'Regra de Transferência VII'),
('EDF473', 'Regra de Transferência III'),
('ART491', 'Regra de Disciplina XV'),
('HIS205', 'Regra de Comportamento I'),
('BIO383', 'Regra de Trabalho de Conclusão XV'),
('BIO373', 'Regra de Comportamento IV'),
('MAT299', 'Regra de Comportamento VI'),
('INF368', 'Regra de Disciplina IX'),
('POR214', 'Regra de Prova Final XIII'),
('ING571', 'Regra de Frequência VIII'),
('ART287', 'Regra de Frequência Mínima VI'),
('ING455', 'Regra de Nota Mínima V'),
('GEO212', 'Regra de Frequência III'),
('HIS238', 'Regra de Disciplina V'),
('POR282', 'Regra de Matrícula II'),
('ART308', 'Regra de Disciplina XIV'),
('QUI506', 'Regra de Comportamento IX'),
('ING490', 'Regra de Matrícula II'),
('POR101', 'Regra de Nota Mínima XIII'),
('INF135', 'Regra de Comportamento XIII'),
('GEO433', 'Regra de Estágio XIV'),
('FIS313', 'Regra de Trabalho de Conclusão XIV'),
('HIS240', 'Regra de Disciplina II'),
('ING515', 'Regra de Avaliação III'),
('ING204', 'Regra de Cancelamento XIV'),
('HIS228', 'Regra de Prova Final II'),
('EDF295', 'Regra de Avaliação V'),
('INF521', 'Regra de Comportamento X'),
('HIS207', 'Regra de Estágio X'),
('HIS324', 'Regra de Estágio III'),
('GEO345', 'Regra de Estágio XV'),
('FIS161', 'Regra de Comportamento II'),
('BIO459', 'Regra de Trabalho de Conclusão VIII'),
('BIO475', 'Regra de Avaliação IV'),
('MAT224', 'Regra de Aprovação VIII'),
('HIS321', 'Regra de Avaliação IX'),
('ART220', 'Regra de Aprovação XII'),
('MAT299', 'Regra de Estágio I'),
('BIO375', 'Regra de Avaliação VIII'),
('QUI347', 'Regra de Disciplina XII'),
('BIO468', 'Regra de Frequência VII'),
('EDF473', 'Regra de Frequência Mínima XV'),
('GEO500', 'Regra de Trabalho de Conclusão XIV'),
('FIS576', 'Regra de Nota Mínima XI'),
('QUI279', 'Regra de Nota Mínima XV'),
('EDF535', 'Regra de Estágio II'),
('FIS581', 'Regra de Cancelamento XIV'),
('EDF216', 'Regra de Disciplina III'),
('BIO246', 'Regra de Prova Final V'),
('BIO383', 'Regra de Estágio I'),
('GEO236', 'Regra de Disciplina XII'),
('INF124', 'Regra de Transferência IV'),
('MAT106', 'Regra de Trabalho de Conclusão V'),
('HIS175', 'Regra de Disciplina III'),
('GEO121', 'Regra de Matrícula III'),
('MAT457', 'Regra de Transferência XII'),
('POR570', 'Regra de Estágio XIV'),
('GEO332', 'Regra de Nota Mínima III'),
('ING265', 'Regra de Estágio IX'),
('QUI107', 'Regra de Atividades Complementares XIV');