
CREATE TABLE PROPRIEDADE (
    id_propriedade     NUMERIC        PRIMARY KEY,
    CPF_proprietario   NUMERIC(11)    NOT NULL,
    Nome               VARCHAR(100)   NOT NULL,
    endereco_cidade    VARCHAR(60)    NOT NULL,
    endereco_estado    VARCHAR(2)     NOT NULL,
    endereco_pais      VARCHAR(60)    NOT NULL,
    endereco_numero    NUMERIC        NOT NULL,
    endereco_CEP       NUMERIC(8)     NOT NULL,
    endereco_bairro    VARCHAR(50)    NOT NULL,
    endereco_pontoref  VARCHAR(100),
    tipo               VARCHAR(30)    NOT NULL,
    n_quartos          NUMERIC        NOT NULL,
    n_banheiros        NUMERIC        NOT NULL,
    preco_noite        NUMERIC(10,2)  NOT NULL,
    max_hospedes       NUMERIC        NOT NULL,
    min_noites         NUMERIC        NOT NULL,
    max_noites         NUMERIC        NOT NULL,
    taxa_limpeza       NUMERIC(10,2),
    datas_disp         DATE,
    hor_checkin        TIME,
    hor_checkout       TIME,
    regra1             VARCHAR(100),
    regra2             VARCHAR(100),
    regra3             VARCHAR(100),
    regra4             VARCHAR(100),
    comodidade1        VARCHAR(100),
    comodidade2        VARCHAR(100),
    comodidade3        VARCHAR(100),
    comodidade4        VARCHAR(100),

    FOREIGN KEY (CPF_proprietario) REFERENCES PROPRIETARIO(CPF)
);